### ISSUE TITLE
Can't install on HAOS 2022.2.5

### ISSUE THREAD

**Issue by enoch85** [DeebotUniverse/Deebot-4-Home-Assistant#110]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

Please see video: https://cloud.danielhansson.nu/s/MBWKCgDMxoRFoLy

Trying to install fails, with a very helpful error message. :)

### On which deebot vacuum you have the issue?

Deebot Pro N8+

### Which version of the Deebot component are you using?

Latest from HACS

### Which version of Home Assistant are you using?

2022.2.5

### What type of installation are you running?

Home Assistant OS

### Country

N/A

### Continent

N/A

### Anything in the logs that might be useful for us?

```txt
[140235846661696] Error handling message: Unknown error
21:59:21 – (ERROR) Home Assistant WebSocket API - message first occurred at 21:55:29 and shows up 4 times
Cannot find integration deebot
21:59:21 – (ERROR) config_entries.py - message first occurred at 21:55:29 and shows up 2 times

```
```


### Additional information

_No response_

**Comment by edenhaus** [comment]
I cannot play your video. Please check if the folder `custom_components/deebot` and if the content is the same as in the zip release folder. If not please reinstall it via Hacs or manually
![Screenshot_20220210-085140](https://user-images.githubusercontent.com/26537646/153361803-0130208b-171f-4960-86f2-d14bf829d5c7.jpg)

**Comment by enoch85** [comment]
@edenhaus But you can download it. ;)

**Comment by edenhaus** [comment]
@enoch85 I have done it too and I get a corruption error. Please do the steps from the comment above.

**Comment by enoch85** [comment]
Hmm OK.

`deboot` doesn't even exist, tried to reinstall, now it works. Sorry for the noise.
