### ISSUE TITLE
没法登陆呢

### ISSUE THREAD

**Issue by huiyanga** [DeebotUniverse/Deebot-4-Home-Assistant#111]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

添加设备登陆，不管选Bumper，还是cloud,都登陆不了

### On which deebot vacuum you have the issue?

T8

### Which version of the Deebot component are you using?

1

### Which version of Home Assistant are you using?

2022.2.2

### What type of installation are you running?

Home Assistant Core

### Country

CN

### Continent

AS

### Instance type

Cloud

**Comment by edenhaus** [comment]
I need more details and please write in english

**Comment by RF8xRF8** [comment]
maybe your device model is T8 max?
T8 max only support TmallGenie because it's Aliyun’s custom device
