### ISSUE TITLE
Not found in Add Integrations

### ISSUE THREAD

**Issue by jn3va** [DeebotUniverse/Deebot-4-Home-Assistant#125]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

I have added the integration in HACS and confirmed the deebot folder is in custom_components.  The files match what is in the git repository.  After restarting homeassistant The integration cannot be found (Integration -> Add -> Deebot 4 Home Assistant.).

### On which deebot vacuum you have the issue?

Vacuum is a T5 but not at that point yet...

### Which version of the Deebot component are you using?

1.2.0

### Which version of Home Assistant are you using?

2022.3.3

### What type of installation are you running?

Home Assistant OS

### Country

US (but haven't gotten to this step)

### Continent

NA (but not at thus step yet)

### Instance type

Cloud

### Anything in the logs that might be useful for us?

```txt
Nothing apparent in logs
```

**Comment by jn3va** [comment]
p.s.   I also tried removing the integration in HACS, restarted home assistant and then re-added deebot 4 home assistant and restarted HA again.  Same result.   Are there any other files that need to be updates for it to show in the add integrations list to check in the config folder?

**Comment by jn3va** [comment]
I decided to try a different browser - I was use MS Edge and switched to Chrome.  Now the integration is listed.  I will leave this open for a bit and if all is well close this tomorrow.

**Comment by zslibra** [comment]
Clean browser cache may help.
