### ISSUE TITLE
Doesn't work with my deebot slim 10

### ISSUE THREAD

**Issue by sagresbier** [DeebotUniverse/Deebot-4-Home-Assistant#135]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

Installation via HACS worked, setup worked, but the commands don't get to the vac
[Log.txt](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/8256232/Log.txt)
.

### On which deebot vacuum you have the issue?

Deebot Ozmo slim 10

### Which version of the Deebot component are you using?

1.19.3

### Which version of Home Assistant are you using?

2022.3.3

### What type of installation are you running?

Home Assistant Container

### Country

de

### Continent

eu

### Instance type

Cloud

**Comment by mrbungle64** [comment]
@sagresbier 

The Deebot Slim 10 is not supported by the deebot-client library:
https://deebot.readthedocs.io/home/faq/
https://deebot.readthedocs.io/integrations/home-assistant/#supported-models
