### ISSUE TITLE
Deebot connection timing out

### ISSUE THREAD

**Issue by ProAdmin007** [DeebotUniverse/Deebot-4-Home-Assistant#140]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

I have installed the Deebot addon and configured the config. But This error keeps coming up.

### On which deebot vacuum you have the issue?

Deebot OZMO 900

### Which version of the Deebot component are you using?

 1.2.0

### Which version of Home Assistant are you using?

Home Assistant 2022.3.6

### What type of installation are you running?

Home Assistant OS

### Country

nl

### Continent

eu

### Instance type

Cloud

### Anything in the logs that might be useful for us?

```txt
Logger: deebot_client.commands.common
Source: /usr/local/lib/python3.9/site-packages/deebot_client/commands/common.py:51
First occurred: 14:41:22 (8 occurrences)
Last logged: 14:41:52

Command "getCleanInfo" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
Command "getBattery" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
Command "getError" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
Command "getSpeed" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
Command "getCachedMapInfo" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
```

**Comment by edenhaus** [comment]
As written on the models list, your model is not supported by this component as it uses the `deebot-client` library
