### ISSUE TITLE
Missing entities/sensors for Deebot T8 AIVI

### ISSUE THREAD

**Issue by TheBigBelgianBastard** [DeebotUniverse/Deebot-4-Home-Assistant#147]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

Hi,

I have two Deebot T8 AIVI robots, one is an EU version and one is a China version. Both work flawlessly with the app (although I have to use different phone due to one being Chinese and one being EU and having different accounts).

Both robots worked flawlessly with the old Deebot integration. Everything worked fine.

With the new Deebot-4-Home-Assistant integration, both robots have basic functionality - start / pause / return to dock. I can also get the robots to clean individual rooms successfully. So the integration is working for the key functions.

The problem I have is the the robots have missing sensors, configuration & diagnostics. All say "disabled by integration". Both robots have identical sensors / configurations / diagnostics disabled. Both robots say "1 device and 23 entities" on the integrations page.

Sensors: the integration has the following sensors reported, but ALL are disabled:
    live map
    last cleaning
    stats time
    stats total area
    stats total cleanings
    stats total time
    stats type

Configuration: the integration has the following configuration items reported, but some are disabled:
    working - life span brush reset 
    working - life span filter reset
    working - life span side brush reset
    disabled - volume
    disabled - water amount
    disabled - advanced mode
    disabled - carpet auto fan speed boost
    disabled - downstairs continuous cleaning

Diagnostic: the integration ha the following diagnostic items, but some are disabled:
    working - relocate
    disabled - mop attached
    disabled - last error
    disabled - life span brush
    disabled - life span filter
    disabled - life span side brush

Thanks for any information that you can give on when some or all of these features may work for the T8 AIVI.

### On which deebot vacuum you have the issue?

Deebot T8 AIVI

### Which version of the Deebot component are you using?

1.2.0

### Which version of Home Assistant are you using?

2022.3.8

### What type of installation are you running?

Home Assistant Supervised

### Country

UK

### Continent

EU

### Instance type

Cloud

**Comment by Edo78** [comment]
Fun fact we are in the very same situation. I too have two Deebot T8 AIVI, one with a Chinese account and one with an EU one.

BTW everything works properly but, as some (or all, not sure) of the entities requires additional computing power there is no reason to enable them all as a default. If you need you can enable them by yourself in the HA UI.

It's written in the documentation here https://deebot.readthedocs.io/integrations/home-assistant/entities/

**Comment by edenhaus** [comment]
@Edo78 Thanks for your help 😊

The sensor are disbaled by default, so we don't make useless requests

**Comment by TheBigBelgianBastard** [comment]
Thank you. I misunderstood what "disabled by integration" meant. I had wrongly assumed it was disabled because it couldn't work with my robot.

I've enabled the ones that I want and they seem to work just fine.

Thank you both for your rapid and helpful replies.
