### ISSUE TITLE
Can't connect to the ecovacs API

### ISSUE THREAD

**Issue by pdecassan** [DeebotUniverse/Deebot-4-Home-Assistant#149]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

Once HACS install is completed (including reboot) I am prompted with the message "Can't connect to the ecovacs API" upon trying to add the integration in Cloud mode.
I cannot see any problems, and have no add blockers etc.

### On which deebot vacuum you have the issue?

Deebot N8+

### Which version of the Deebot component are you using?

1.2.0

### Which version of Home Assistant are you using?

2022.3.8

### What type of installation are you running?

Home Assistant OS

### Country

Gb

### Continent

Ww

### Instance type

Cloud

**Comment by edenhaus** [comment]
Please activate [debug logs](https://deebot.readthedocs.io/integrations/home-assistant/issues/) and add it here. Without I cannot help you

**Comment by pdecassan** [comment]
Thank you @edenhaus for the prompt response.
I was using "GB" as the country code for Great Britain and this threw the "cant connect error". Once I amended this to "UK" it connected. Might be useful to reflect this in the error message.
Kind regards.
