### ISSUE TITLE
Deebot T9 AIVI wont show rooms or update them

### ISSUE THREAD

**Issue by hasi87** [DeebotUniverse/Deebot-4-Home-Assistant#164]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

I noticed my Deebot T9 AIVI wont show me rooms or numbers at his attributes.
Also it won't update or show up if i try to trigger an update via the deebot service.

I already checked the docs but couldn't find anything similar.
I have labeled all my rooms, now i noticed some errors in the logfiles which seeems to correspond to the rooms property.

```
    Could not parse getMapSubSet: {'type': 'ar', 'subtype': '15', 'connections': '7,', 'name': 'Levin', 'seqIndex': 0, 'seq': 0, 'count': 0, 'totalCount': 50, 'index': 0, 'cleanset': '1,0,2', 'valueSize': 633, 'compress': 1, 'center': '-6775,-9225', 'mssid': '8', 'value': 'XQAABAB5AgAAABaOQok5MfkIKbGTBxaUTX13SjXBAI1/Q3A9Kkx2gYZ1QdgwfwOSlU3hbRjNJYgr2Pr3WgFez3Gcoj3R2JmzAuc436F885ZKt5NF2AE1UPAF4qq67tK6TSA64PPfmZQ0lqwInQmqKG5/KO59RyFBbV1NKnDIGNBGVCWpH62WLlMu8N4zotA8dYMQ/UBMwr/gddQO5HU01OQM2YvF', 'mid': '98100521'}
    Could not parse getMapSubSet: {'type': 'ar', 'subtype': '15', 'connections': '7,', 'name': 'Kids 1', 'seqIndex': 0, 'seq': 0, 'count': 0, 'totalCount': 50, 'index': 0, 'cleanset': '1,0,2', 'valueSize': 633, 'compress': 1, 'center': '-6775,-9225', 'mssid': '8', 'value': 'XQAABAB5AgAAABaOQok5MfkIKbGTBxaUTX13SjXBAI1/Q3A9Kkx2gYZ1QdgwfwOSlU3hbRjNJYgr2Pr3WgFez3Gcoj3R2JmzAuc436F885ZKt5NF2AE1UPAF4qq67tK6TSA64PPfmZQ0lqwInQmqKG5/KO59RyFBbV1NKnDIGNBGVCWpH62WLlMu8N4zotA8dYMQ/UBMwr/gddQO5HU01OQM2YvF', 'mid': '98100521'}

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 52, in wrapper
    response = func(cls, event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 108, in __handle_body_data
    return cls._handle_body_data(event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 97, in _handle_body_data
    return cls._handle_body_data_dict(event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/commands/map.py", line 223, in _handle_body_data_dict
    subtype=cls._ROOM_NUM_TO_NAME[subtype] if subtype else None,
KeyError: '15'

```

One of my rooms were named "Levin".
When i saw this error i renamed it to "Kids 1" in the Ecovacs App and triggered a rooms update via the HA service.
It seems it's not the name specifically which he couldn't parse.
It still wont show me any rooms when i look at the deebot attributes.

The only attribute I am seeing is "Last error".
Also the live map entity wont show up, but i don't know if that's also related to this issue.

Can someone point me in the right direction for solving this issue?

### Diagnostics information

[deebot-dd705cd1b0945ac97a87d94f8a8951de-BB-8-3917517a941d01e74d6f1ee718afb0f7.json(1).txt](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/8549365/deebot-dd705cd1b0945ac97a87d94f8a8951de-BB-8-3917517a941d01e74d6f1ee718afb0f7.json.1.txt)

### Anything in the logs that might be useful for us?

```txt
Could not parse getMapSubSet: {'type': 'ar', 'subtype': '15', 'connections': '7,', 'name': 'Levin', 'seqIndex': 0, 'seq': 0, 'count': 0, 'totalCount': 50, 'index': 0, 'cleanset': '1,0,2', 'valueSize': 633, 'compress': 1, 'center': '-6775,-9225', 'mssid': '8', 'value': 'XQAABAB5AgAAABaOQok5MfkIKbGTBxaUTX13SjXBAI1/Q3A9Kkx2gYZ1QdgwfwOSlU3hbRjNJYgr2Pr3WgFez3Gcoj3R2JmzAuc436F885ZKt5NF2AE1UPAF4qq67tK6TSA64PPfmZQ0lqwInQmqKG5/KO59RyFBbV1NKnDIGNBGVCWpH62WLlMu8N4zotA8dYMQ/UBMwr/gddQO5HU01OQM2YvF', 'mid': '98100521'}
    Could not parse getMapSubSet: {'type': 'ar', 'subtype': '15', 'connections': '7,', 'name': 'Kids 1', 'seqIndex': 0, 'seq': 0, 'count': 0, 'totalCount': 50, 'index': 0, 'cleanset': '1,0,2', 'valueSize': 633, 'compress': 1, 'center': '-6775,-9225', 'mssid': '8', 'value': 'XQAABAB5AgAAABaOQok5MfkIKbGTBxaUTX13SjXBAI1/Q3A9Kkx2gYZ1QdgwfwOSlU3hbRjNJYgr2Pr3WgFez3Gcoj3R2JmzAuc436F885ZKt5NF2AE1UPAF4qq67tK6TSA64PPfmZQ0lqwInQmqKG5/KO59RyFBbV1NKnDIGNBGVCWpH62WLlMu8N4zotA8dYMQ/UBMwr/gddQO5HU01OQM2YvF', 'mid': '98100521'}

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 52, in wrapper
    response = func(cls, event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 108, in __handle_body_data
    return cls._handle_body_data(event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 97, in _handle_body_data
    return cls._handle_body_data_dict(event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/commands/map.py", line 223, in _handle_body_data_dict
    subtype=cls._ROOM_NUM_TO_NAME[subtype] if subtype else None,
KeyError: '15'
```

**Comment by edenhaus** [comment]
Currently custom room names are not supported. Hopefully I have time the next week to implement it, but no guarantee.

**Comment by Mani-1992** [comment]
OK.
But you mean if i reset the map let him label them by itself it should work?

Can i still join 2 rooms together if i don't try to relabel them?

**Comment by edenhaus** [comment]
> But you mean if i reset the map let him label them by itself it should work?

I think so, but I have only the 950, which does not support custom naming

**Comment by hasi87** [comment]
Hi.

Just wanted to let you know that i have reset the T9 AIVI via the reset button and added him back.
After 2 complete cleanups i removed the old robot and added the "new" one back to HA.
Basically i also changed the name of the bot.

For some reason it seems to work.
Now i can see the live map as expected and i have rooms in the attributes.

I also can divide and combine them.
He is perfectly fine with renaming the rooms also.
By labelling the rooms i can now differentiate them and use them in the UI.

I'm perfectly fine with using the labels as room names for now.

thanks for this awesome integration by the way. :)
