### ISSUE TITLE
Empty Dustbin

### ISSUE THREAD

**Issue by vandalon** [DeebotUniverse/Deebot-4-Home-Assistant#174]
### Question

Hi, is there any way to start the "empty dustbin" routine (for emptying the vacuum's dustbin in the docking station's dustbin/bag) via the add-on? I've found a similar question with a reference to a discussion that no longer exists so I still don't know the answer :D

**Comment by Edo78** [comment]
Yes, there is.

You should check the example on how to [send custom commands](https://deebot.readthedocs.io/integrations/home-assistant/events/#deebotcustomcommand) and the spec on the [`setAutoEmpty` command](https://deebot.readthedocs.io/advanced/data_types/json/commands/auto_empty/#setautoempty)

**Comment by vandalon** [comment]
I'm sorry, i did not read the docs well enough. I figured the setAutoEmpty would only enable or disable the feature. If only i've read a bit more i would've seen the start option... Sorry

**Comment by edenhaus** [comment]
No problem. I will close it as no further action is required :)
Unfortunately ecovacs has specified the command in this "missunderstanding" way
