### ISSUE TITLE
Ability to trigger "Empty to Bin"

### ISSUE THREAD

**Issue by mayanez** [DeebotUniverse/Deebot-4-Home-Assistant#180]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my feature request or idea

### Is your feature request related to a problem?

Currently, my Deebot is configured to auto-empty when finishing a clean. However, I'd like to schedule this independently of when the clean happens. I have the Deebot run overnight and the emptying suction is extremely load. I'd prefer to run it sometime during the day before it runs at night. 

Im not sure if the API supports this as I didnt see it in the client library. If it does and it's a matter of extending the client then I'd be happy to contribute if pointed in the right direction.

### Suggested solution

Extend client.py if available functionality exists via cloud API.

**Comment by edenhaus** [comment]
This is already possible using a [custom command](https://deebot.readthedocs.io/integrations/home-assistant/events/#deebotcustomcommand). Please refer also to [setAutoEmpty](https://deebot.readthedocs.io/advanced/data_types/json/commands/auto_empty/#setautoempty)

As the api gives us no possibility to find out, which features each models supports, we need to create this by our own. Until this happens, you only have the possibility to use the custom command described above.

**Comment by Edo78** [comment]
It is already possible.
Check my answer to a previous issue https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues/174#issuecomment-1125906407
