### ISSUE TITLE
No camera domain for Deebot Ozmo T8+

### ISSUE THREAD

**Issue by MarkLyck** [DeebotUniverse/Deebot-4-Home-Assistant#188]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

I've setup Deebot 4 Home Assistant and the sensors and commands all work fine.

However no camera domain got set up for me.

The Deebot Ozmo T8+ does support live map in the official app.

This ticket is a duplicate of: https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues/178

But the OP @msavazzi did not provide diagnostic information and the ticket was closed. In this ticket i am providing the diagnostic information below:

Here's what i see in Home assistant:

sensors:
![Screen Shot 2022-05-31 at 11 52 29](https://user-images.githubusercontent.com/6841110/171216483-242401ec-c8cd-452a-8eba-1c549c9559c5.png)

The "live map" sensor shows up, but if I click it I get this error:
![Screen Shot 2022-05-31 at 11 55 23](https://user-images.githubusercontent.com/6841110/171217069-82c2222d-45e7-4d2c-b921-1d5571f47494.png)

configuration and diagnostics
![Screen Shot 2022-05-31 at 11 52 44](https://user-images.githubusercontent.com/6841110/171216535-bea9598d-a03a-4744-869f-90db86615136.png)

no camera entities either.
![Screen Shot 2022-05-31 at 11 53 14](https://user-images.githubusercontent.com/6841110/171216630-9cd2b676-4c2a-4ae5-90e0-16046eaa3272.png)

### Diagnostics information

[deebot-5e9a2c403b11be3cfdceac06a39edf3a-Vacuum-ed77c3b94b720de3331d12b0c6ad6675.json.txt](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/8806763/deebot-5e9a2c403b11be3cfdceac06a39edf3a-Vacuum-ed77c3b94b720de3331d12b0c6ad6675.json.txt)

**Comment by edenhaus** [comment]
#178 is not closed it was only marked as stale.

You need to activate the sensors/camera what you need. They are disabled by default as written in the docs.
Please enabled it. If afterwards the issue still exists please comment in #178.

Duplicate of #178

**Comment by MarkLyck** [comment]
@edenhaus ahh you are totally right. 🤦‍♂️

I skipped over that info section multiple times reading the docs 😰. Perhaps change the info box to a warning box or mention it on the setup page would make it more obvious for newbies who haven't seen disabled entities before. 

For anyone else who either overlooked that 1 info line in the docs too or like me haven't manually enabled entities before this is how to get it working:

To enable the extra  entities (like the camera and other sensors):
1. Go to device page for your vacuum in home assistant
2. Click on the sensor / camera you want to enable
3. Click "Advanced settings"
4. Click "enable" and it should show up after 30 seconds.

**Comment by edenhaus** [comment]
It‘s now an `attention` box, thanks for the suggestion 😊
