### ISSUE TITLE
Setup (Integration) doesn't do anything

### ISSUE THREAD

**Issue by jh20001** [DeebotUniverse/Deebot-4-Home-Assistant#195]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed/try to install the latest version

### The problem

Hello!

So I updated everything (HA, HACS, and installed the latest non-beta version of this from within HACS). I then head over to the integrations screen, find it in the add integration window, fill in my info (user, pass, us, na or ww) and click the button. It then starts to process the information and the popup becomes empty (title bar with "?" icon, and close bottom below--nothing else). I close it and nothing ever happens after that. Nothing shows in the integrations screen as being added. No devices, entities, or anything else. I reboot, I try again and again, and the same result every time. I finally gave up :(

### On which deebot vacuum you have the issue?

Deebot Ozmo 930

### Which version of the Deebot component are you using?

930

### Which version of Home Assistant are you using?

2022.6.6

### What type of installation are you running?

Home Assistant Container

### Country

us

### Continent

na (or ww)

### Instance type

Cloud

### Anything in the logs that might be useful for us?

```txt
Nothing shows in the logs that I could see
```

**Comment by mrbungle64** [comment]
@jh20001 

The Deebot OZMO 930 is not supported by the deebot-client library (used by [Deebot for Home Assistant](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant)):
https://deebot.readthedocs.io/home/faq/
https://deebot.readthedocs.io/home/models/#deebot-client

But you can install the [Node-RED add-on](https://github.com/hassio-addons/addon-node-red) and use [Ecovacs Deebot node for Node-RED](https://github.com/mrbungle64/node-red-contrib-ecovacs-deebot).

**Comment by jh20001** [comment]
Well *pile of poop*. Oh well. The official integration doesn't support it either it seems. It shows it in the list of devices, but there is no command to send it to clean. Oh Well :( Thanks!
