### ISSUE TITLE
"Failed to get devices" adding new Deebot

### ISSUE THREAD

**Issue by ABredhauer** [DeebotUniverse/Deebot-4-Home-Assistant#196]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

I've just purchased anew Deebot (N8+) and have added it to the mobile app. I was expecting it to automatically appear in HA via the integration but it hasn't.

### Diagnostics information

No device yet to download diagnostics

### Anything in the logs that might be useful for us?

```txt
Traceback (most recent call last):
  File "/config/custom_components/deebot/hub.py", line 103, in _check_status_task
    await self._check_status_function()
  File "/config/custom_components/deebot/hub.py", line 113, in _check_status_function
    devices = await self._api_client.get_devices()
  File "/usr/local/lib/python3.9/site-packages/deebot_client/api_client.py", line 61, in get_devices
    raise ApiError(f"failure {resp['error']} ({resp['errno']}) on getting devices")
KeyError: 'error'
```

**Comment by edenhaus** [comment]
Can you please attach [debug logs](https://deebot.readthedocs.io/integrations/home-assistant/issues/).

**Comment by ABredhauer** [comment]
[home-assistant-deebot-debug.log](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/8953838/home-assistant-deebot-debug.log)

Debug Log attached - I've tried to remove the non deebot lines from the log
