### ISSUE TITLE
Adding a new robot after initial HA install

### ISSUE THREAD

**Issue by robfgreenwood** [DeebotUniverse/Deebot-4-Home-Assistant#198]
### Question

Hi - I've added a second Deebot robot (OZMO 920) to my Deebot account, my first robot works nicely in the setup (also an OZMO 920), but I can't work out how to get the integration to pick up the new one.  Tried re-starting HA etc. and the add new entities automatically is turned on.  Just doesn't seem to pick it up.  Could you advise how to get the module to recognise and create the entities for the new robot - do I need to re-install it?

Thanks, Rob

**Comment by edenhaus** [comment]
Currently you need to reconfigure the integration. A reinstall via Hacs is not required.

I plan to add this functionallity via the Options-Button, but I don't have time until the end of summer 😬

**Comment by robfgreenwood** [comment]
> Currently you need to reconfigure the integration. A reinstall via Hacs is not required.
> 
> I plan to add this functionallity via the Options-Button, but I don't have time until the end of summer 😬

Thanks for the response and excuse my next question, when you say reconfigure what do you mean?  Delete and run a setup again?

**Comment by edenhaus** [comment]
Go to Settings -> Devices & Services and delete there the Deebot 4 HomeAssistant entry. Afterwards please add it again and select both devices.
