### ISSUE TITLE
Battery level as entity?

### ISSUE THREAD

**Issue by stueng** [DeebotUniverse/Deebot-4-Home-Assistant#209]
### Question

Hi, I am a little confused because the entity "screen" (not sure what the proper word is? shows the battery level of the robot

![image](https://user-images.githubusercontent.com/33299988/177784071-3127d55d-b0c8-4028-84eb-c9ee50d32783.png)

But when looking at the states in dev settings, or searching out entities the battery level does not appear anywhere as an entity which can be used in dashboards/automations etc.

Any ideas how I can obtain the battery level as an entity?

**Comment by edenhaus** [comment]
Currently the battery level is available as attribute in the vacuum entity. Automation can trigger also on attributes.

It's also possible to create a battery sensor entity, but until August I'm on vacation so please be patient

**Comment by vandalon** [comment]
Also, you can use a template sensor in HA to extract the attribute and create a separate sensor for this goal if need be.
