### ISSUE TITLE
Deebot integration is not showing

### ISSUE THREAD

**Issue by edersong** [DeebotUniverse/Deebot-4-Home-Assistant#211]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

Installed the Deebot 4 Home assistant from HACS and restarted HA, but when trying to add integration it's not being showed.

![HACS Installed](https://user-images.githubusercontent.com/64137913/177959387-29d1d8d2-d545-4bb1-8fac-ba2b0a723956.png)
![Integration not showing](https://user-images.githubusercontent.com/64137913/177959410-81a93155-6feb-4223-a46f-a8eaf742b682.png)
.

### Diagnostics information

No related erros were found at the logs

**Comment by edenhaus** [comment]
Try to reinstall it via HACS.
If the problem still exists, please verify that the folder `custom_components/deebot` exists in your configuration folder

**Comment by edersong** [comment]
Yes, tried reinstalling it including the previous version but without luck,
Sure, the deboot directory exists under my custom_components directory

![config](https://user-images.githubusercontent.com/64137913/177965792-208edf1b-42fb-46ea-8448-92e145c7e7b6.png)

**Comment by edenhaus** [comment]
Please check your logs. There must be something, where HA tries to install `deboot-client`

**Comment by edersong** [comment]
There is no related entries at the logs

![No_logs](https://user-images.githubusercontent.com/64137913/177973928-20c2fa83-3534-4c75-af96-2285e5b3338a.png)

**Comment by edenhaus** [comment]
Please activate debugs logs and open the log-file in a texteditor. Then you must find some logs, where home assistant tries to set up the integration.

**Comment by edersong** [comment]
There is no way to activate debug since I cannot add the integration.
At the HACS, there is no option to enable debug.

**Comment by edersong** [comment]
I didn't perform anything more and now it's working. weird.
