### ISSUE TITLE
Send Deebot to position on map

### ISSUE THREAD

**Issue by liveware-problems** [DeebotUniverse/Deebot-4-Home-Assistant#221]
### Question

Not sure if this is possible for a Deebot - or if anyone knows of a workaround to accomplish sending the Deebot to a specific location on the map and waiting there for the dust bin to be emptied?

I'm thinking a script or similar to send the bot to a location and then stop or pause the bot, which can then be followed by a 'return_to_base' command.

Is there a custom command that can be used to send to a specific location? I know I can send to a custom area, but would need to then find a way to interrupt it from returning home. Anyone got any ideas?

Thanks in advance!

**Comment by edenhaus** [comment]
There exist unfortunately no command for this. The only workaround that I can imagine is that you write an automation, which pause the robot, when he is returning to the base.

**Comment by liveware-problems** [comment]
That's basically the approach I have taken; I used the following script to send it to clean a location near the bin, and then stop the vacuum when it is about to return home. I then use another button to send it back to base.

`
  deebot_maint_position:
    alias: HollyBotMaintenance
    sequence:
      - service: vacuum.send_command
        data:
          entity_id: vacuum.deebot
          command: custom_area
          params: 
            coordinates: 1100,3895,1160,4125          
      - wait_for_trigger:
          - platform: state
            entity_id:
              - vacuum.deebot
            to: returning
      - service: vacuum.stop
        data: 
          entity_id: vacuum.deebot
    mode: single
`

Happy to close this now, thanks for the integration and the reply! :-)
