### ISSUE TITLE
Template Error

### ISSUE THREAD

**Issue by GilGedje** [DeebotUniverse/Deebot-4-Home-Assistant#223]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed/try to install the latest version

### The problem

every thing is working but the selecting locations to clean.
i get a template error in the log:

```jinja2
Template variable error: 'trigger' is undefined when rendering '{% set room_name = "living room" %} {% set queue = trigger.to_state.state.split(",") %} {{ queue.index(room_name)+1 if room_name in queue else 0 }}'
Template variable error: 'trigger' is undefined when rendering '{% set room_name = "kitchen" %} {% set queue = trigger.to_state.state.split(",") %} {{ queue.index(room_name)+1 if room_name in queue else 0 }}'
Template variable error: 'trigger' is undefined when rendering '{% set room_name = "bedroom" %} {% set queue = trigger.to_state.state.split(",") %} {{ queue.index(room_name)+1 if room_name in queue else 0 }}'
```

i dont have any idea how to make this work - is there a chance i can have some help?

### On which deebot vacuum you have the issue?

Yeedi mop pro

### Which version of the Deebot component are you using?

1.4.1

### Which version of Home Assistant are you using?

2022.07.0

### What type of installation are you running?

Home Assistant OS

### Country

il

### Continent

ww

### Instance type

Bumper

**Comment by mrbungle64** [comment]
@GilGedje 

fyi: the Yeedi mop pro (and yeedi in general) are currently not supported.
https://deebot.readthedocs.io/home/faq
https://deebot.readthedocs.io/home/models/

**Comment by mrbungle64** [comment]
@GilGedje 

Btw: Why you removed the log output?

**Comment by GilGedje** [comment]
just like that... not particular reason

> @GilGedje
> 
> Btw: Why you removed the log output?

**Comment by skalec** [comment]
i have exact the same Problem and need help too. What is needed to help us?

**Comment by mrbungle64** [comment]
@GilGedje @skalec 

fyi: @edenhaus is currently on an extended vacation.
It will probably take some weeks until he will be active here again.

**Comment by skalec** [comment]
Thanks for Info.

**Comment by edenhaus** [comment]
Can you please post your the part of your yaml configuration, otherwise it will be hard to help you

**Comment by skalec** [comment]
Sry a little bit late

`template:
  - unique_id: deebot_robo_queue
  - trigger:
      - entity_id: input_text.deebot_robo_queue
        platform: state
  - sensor:
      - unique_id: deebot_robo_queue_living_room
        name: deebot_robo_queue_living_room
        state: >
          {% set room_name = "Living room" %}
          {% set queue = trigger.to_state.state.split(",") %}
          {{ queue.index(room_name)+1 if room_name in queue else 0 }}
      - unique_id: deebot_robo_queue_bathroom
        name: deebot_robo_queue_bathroom
        state: >
          {% set room_name = "Bathroom" %}
          {% set queue = trigger.to_state.state.split(",") %}
          {{ queue.index(room_name)+1 if room_name in queue else 0 }}
      - unique_id: deebot_robo_queue_kitchen
        name: deebot_robo_queue_kitchen
        state: >
          {% set room_name = "Kitchen" %}
          {% set queue = trigger.to_state.state.split(",") %}
          {{ queue.index(room_name)+1 if room_name in queue else 0 }}
      - unique_id: deebot_robo_queue_corridor
        name: deebot_robo_queue_corridor
        state: >
          {% set room_name = "Corridor" %}
          {% set queue = trigger.to_state.state.split(",") %}
          {{ queue.index(room_name)+1 if room_name in queue else 0 }}`
