### ISSUE TITLE
Deebot 950 not update the status of device. All sensor is unavailable

### ISSUE THREAD

**Issue by andrearomanoif** [DeebotUniverse/Deebot-4-Home-Assistant#229]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

for some days I have this problem and the component is unable to update the information from the server. With the application of ecovacs everything works normally. 
Integration has been working with this robot for several months

### Diagnostics information

Logger: deebot_client.commands.common
Source: /srv/homeassistant/lib/python3.9/site-packages/deebot_client/commands/common.py:51
First occurred: 21:27:49 (18 occurrences)
Last logged: 21:27:51

Command "getBreakPoint" was not successfully: {'ret': 'fail', 'errno': 4200}
Command "getCarpertPressure" was not successfully: {'ret': 'fail', 'errno': 4200}
Command "getBattery" was not successfully: {'ret': 'fail', 'errno': 4200}
Command "getSpeed" was not successfully: {'ret': 'fail', 'errno': 4200}
Command "getCachedMapInfo" was not successfully: {'ret': 'fail', 'errno': 4200}

**Comment by mrbungle64** [comment]
@andrearomanoif 

> Command "getBreakPoint" was not successfully: {'ret': 'fail', 'errno': 4200}
> Command "getCarpertPressure" was not successfully: {'ret': 'fail', 'errno': 4200}
> Command "getBattery" was not successfully: {'ret': 'fail', 'errno': 4200}
> Command "getSpeed" was not successfully: {'ret': 'fail', 'errno': 4200}
> Command "getCachedMapInfo" was not successfully: {'ret': 'fail', 'errno': 4200}

The error code 4200 indicates that your device has poor WiFi connection.

> Source: /srv/homeassistant/lib/python3.9/site-packages/deebot_client/commands/common.py:51

And Python 3.9 is not supported anymore. This will be the actual problem.

**Comment by andrearomanoif** [comment]
@mrbungle64 Thanks a lot for the answer.
I don't think there is a connection problem. The vacuum cleaner is correctly connected to WiFi and works with its app. From the same app the signal level is reported as "strong". The vacuum cleaner is located right next to the router.

Regarding python version 3.9, however, I would like some clarification. Perhaps this is a coincidence but the error could have started in the transition from version 2022.7.5 to version 2022.7.7. I don't think this has brought about a python update. I also tried a downgrade but the problem persists. If you have any other useful information I would be able to.

**Comment by mrbungle64** [comment]
@andrearomanoif 

> @mrbungle64 Thanks a lot for the answer. I don't think there is a connection problem. The vacuum cleaner is correctly connected to WiFi and works with its app. From the same app the signal level is reported as "strong". The vacuum cleaner is located right next to the router.

This could have been a temporary problem. Do these messages still appear in the log?

> 
> Regarding python version 3.9, however, I would like some clarification. Perhaps this is a coincidence but the error could have started in the transition from version 2022.7.5 to version 2022.7.7. I don't think this has brought about a python update. I also tried a downgrade but the problem persists. If you have any other useful information I would be able to.

What do you exactly mean?

You can find some additional information in [this issue](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues/222#issuecomment-1191832888)

**Comment by andrearomanoif** [comment]
Yes, the errors have been active for two days.
I tried to restart and do other actions but nothing done.

**Comment by mrbungle64** [comment]
@andrearomanoif 

As I already mentioned (assuming that you are running version 1.4.0 or above) the actual problem will be that Python 3.9 is not supported anymore. [Version 1.4.0 and above require HA 2022.7 and implizit python 3.10](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues/222#issuecomment-1191832888).

**Comment by andrearomanoif** [comment]
OK thanks. I will try to install Python 3.10 as soon as possible.
You have a step by step guide to upgrade Python to debian (I have a raspberry py 4).
I use the core version of HA and not hassio.
Thanks for the support

**Comment by edenhaus** [comment]
Sorry we can't give you support for the HA core update   and the underlaying python 3.10 update, but you can try to search for help in the HA forum.

For the other problem, please open a issue again after the python 3.10 upgrade, if it still persists

**Comment by andrearomanoif** [comment]
I managed to upgrade to python 3.12 and the problem was solved.
Thanks so much for the support
