### ISSUE TITLE
login succesfull - but no deebot -.-

### ISSUE THREAD

**Issue by crosserSniper** [DeebotUniverse/Deebot-4-Home-Assistant#231]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed/try to install the latest version

### The problem

Dear everyone,

when I try to implement my Deebot OZMO 930, I could log in (tried also with wrong login - error msg), but my deebot is not shown after login.
What I'm doing wrong? 
Is the Deebot OZMO 930 compatible?

### On which deebot vacuum you have the issue?

DEEBOT OZMO 930

### Which version of the Deebot component are you using?

1.9.9

### Which version of Home Assistant are you using?

2022.8.3

### What type of installation are you running?

Home Assistant Supervised

### Country

de

### Continent

eu

### Instance type

Cloud

### Additional information

![grafik](https://user-images.githubusercontent.com/110885066/184474089-e973b943-f86f-4677-bedf-886ff965cb33.png)
![grafik](https://user-images.githubusercontent.com/110885066/184474103-5a6912f1-2f69-4f22-ae2d-131c77ebb7bf.png)
![grafik](https://user-images.githubusercontent.com/110885066/184474119-bcf7772a-a1c9-4a19-9ab4-e236165f5f06.png)
![grafik](https://user-images.githubusercontent.com/110885066/184474135-ea7dd1a2-0a83-4793-a118-fe2bf6cd586c.png)

**Comment by mrbungle64** [comment]
@crosserSniper 

> Is the Deebot OZMO 930 compatible?

No, as you can see if you follow the links from the [FAQ](https://deebot.readthedocs.io/home/faq/) and [documentation](https://deebot.readthedocs.io/integrations/home-assistant) (see above).

If you want to use the OZMO 930 in Home Assistant you can install the [Node-RED add-on](https://github.com/hassio-addons/addon-node-red) and use [Ecovacs Deebot node for Node-RED](https://github.com/mrbungle64/node-red-contrib-ecovacs-deebot).

**Comment by crosserSniper** [comment]
Thanks! 
I thought all the Deebots are supportet - but I see the 930 is only supported by Ecovacs Deebot adapter
