### ISSUE TITLE
Cannot connect ECOVACSHOME server

### ISSUE THREAD

**Issue by xyzsesame** [DeebotUniverse/Deebot-4-Home-Assistant#232]
### Question

Hi Guys

After i fill the SSID, Password, Country, Contient, it show fail to connect server.
Contry: CN
Contient: WW

anyone knows what's problem?

**Comment by sympapa** [comment]
@xyzsesame 

Hello.
I don't know the cause, but you may not be able to log in with the continent set to "ww".

In the case of the "Example app" in the following URL, I was able to log in without continent setting and find my continent, so you may want to try this application.
(*This is not an integration for Home Assistant)
https://github.com/mrbungle64/ecovacs-deebot.js/wiki/Usage

Good luck.

**Comment by edenhaus** [comment]
Can you please activate debug logs and check them afterwards. There should be more information.

@sympapa The continent will be ignored, if you specify China as country
