### ISSUE TITLE
Deebot 901

### ISSUE THREAD

**Issue by chris8837** [DeebotUniverse/Deebot-4-Home-Assistant#235]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

I  have a 901 that used to work with the ligio integration but it stopped from an update recently. I think python.  So I’m trying to use this. It finds the account and adds the robot but I can’t control it. When I hit the play button it logs an error and nothing starts

### Diagnostics information

This error originated from a custom integration.

Logger: deebot_client.commands.common
Source: custom_components/deebot/vacuum.py:235 
Integration: Deebot 4 Home Assistant (documentation, issues) 
First occurred: 10:59:56 PM (1 occurrences) 
Last logged: 10:59:56 PM

Command "clean" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}

**Comment by edenhaus** [comment]
As specified in the docs, this integration unfortunately is not supporting your model.
I don't have a model, which uses your protocol and therefore it's hard to implement the support.
If you have the technical skills to implement it, please feel free to open a PR
