### ISSUE TITLE
Multiple Vacuums Support

### ISSUE THREAD

**Issue by robertwigley** [DeebotUniverse/Deebot-4-Home-Assistant#238]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

I have just added a second vacuum to my Ecovacs account and am unable to see it in Home Assistant despite reloading the integration and both restarting Home Assistant as performing a full reboot of the host (Raspberry Pi).

Are multiple vacuums supported? Both vacuums are the T8 AIVI and are assigned to the same Home in the Ecovacs app rather than a second Home. However, I did also try creating a second Home and assigning the second vacuum to tha, but it didn't make any difference.

I've read through the entire documentation and can't see any mention of multiple vacuums other than in the Issues section where it states "If you have multiple vacuums please add the logs only for the relevant one." which leads me to believe that it is supported. Please can someone confirm whether this is the case or not, and, if it is, how to force a refresh to pull in the second device (vacuum) and related entitites (and maybe update the documentation to help others). Many thanks.

### Diagnostics information

[deebot-3fac25e3f790a87fac8614ea8316a198-Downstairs-db3075fe6280b19cb438b0b10e7fb02a.json.txt](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/9417176/deebot-3fac25e3f790a87fac8614ea8316a198-Downstairs-db3075fe6280b19cb438b0b10e7fb02a.json.txt)

### Additional information

I also created an issue under docs. Item 173 as the documentation may need to be updated.

**Comment by edenhaus** [comment]
Multiple vacuum are already supported only the configuration cannot be changed after setup. As workaround you can delete the config entry and set it up again. Than you should be able to select also the second vacuum. Please let me know if this is not working.

I propose to use the option feature to select vacuum after setup, but i need time to implement it.

**Comment by robertwigley** [comment]
@edenhaus Thank you for your response. Deleting the integration and readding it has brought the new second vacuum in. It would be worthwhile updating the documentation to indicate this is needed. Thanks again and keep up the excellent work on this, one of my most used integrations.
