### ISSUE TITLE
All infos are missing from my 2 deebot

### ISSUE THREAD

**Issue by cagnulein** [DeebotUniverse/Deebot-4-Home-Assistant#244]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

I have 2 deebot, and both of them are recognizied from this integration but all the proprieties of these devices stay to "unknown".
I try several restart and it's always the same.
I started this because of #225 @edenhaus 

I see a lot of `{'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}`

Let me know if you need any other information

### Diagnostics information

[log.txt](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/9596845/log.txt)
relevant debug log

**Comment by mrbungle64** [comment]
@cagnulein 

You are using 2 Deebot OZMO 905, right?
This model is not supported by this integration.
https://deebot.readthedocs.io/home/models/

**Comment by cagnulein** [comment]
yes @mrbungle64 hah ok sorry, i saw the devices so I thought that it was supported. Thanks

**Comment by edenhaus** [comment]
@cagnulein If you have the technical skills to implement the support for your models feel free to contact me.
Older models (like your robots) use xml ober mqtt instead of json over mqtt (newer models, supported by this integration)

**Comment by cagnulein** [comment]
@edenhaus got it, thanks. I will have to find the time, and actually all my spare time is in this project https://github.com/cagnulein/qdomyos-zwift

**Comment by edenhaus** [comment]
Unfortunately I cannot implement it for you as I don't have a robot that uses xml and ecovacs is not giving us information about their api
