### ISSUE TITLE
Set "True Detect" on Deebot T8/N8/T9 

### ISSUE THREAD

**Issue by nickw444** [DeebotUniverse/Deebot-4-Home-Assistant#254]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my feature request or idea

### Is your feature request related to a problem?

For some users (including me), Deebot's True Detect Obstacle Avoidance functionality does not work well in some rooms of the house where there are reflective kickboards at robot level. The reflections cause the robot to believe there is an obstacle in the way, and thus results in the robot doing circles in these areas and not cleaning the space.

### Suggested solution

It would be great if this integration supported controlling this parameter of the robot.  I have implemented this functionality previously in my client library for the Deebot T8, but am looking to move to this integration as something with better support (including map view)

https://github.com/nickw444/deebot-t8/blob/dcf2015cb050d19d93afe17656c3a16737e08079/deebot_t8/entity.py#L411-L417

### Api example request

https://github.com/nickw444/deebot-t8/blob/dcf2015cb050d19d93afe17656c3a16737e08079/deebot_t8/entity.py#L411-L417

**Comment by edenhaus** [comment]
Yes of course we can extend this integration by this command 😊
Currently I‘m two weeks on vacation, but if you want you can submit directly a PR in the library.
This command should be implemented similar to https://github.com/DeebotUniverse/client.py/pull/157. It should be straight forward, but if you have any questions don‘t hesitate to ask.
Also if your model supports other things than the 950, please feel free to open an PR 😊

**Comment by edenhaus** [comment]
Also my must thank you 🙏 as I got inspired from your authenticator and used it also in the library 😊

**Comment by nickw444** [comment]
Thanks, yep I'll have a crack at implementing a PR for this change at some point this week. 

Glad you took some inspiration from my implementation for authentication 😆

**Comment by nickw444** [comment]
PRs are up! 

- https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/pull/255
- https://github.com/DeebotUniverse/client.py/pull/163

I do have to say; the client library is very easy to extend and add functionality to 💯
