### ISSUE TITLE
Unable to Control T8 AIVI

### ISSUE THREAD

**Issue by ph0nebooth** [DeebotUniverse/Deebot-4-Home-Assistant#262]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [x] I have installed the latest version

### The problem

My Deebot 4 Home Assistant HACS integration has stopped working. The integration receives status updates from the Ecovacs cloud but I'm unable to issue control commands to the device.

I have completed removed the integration from HACS and reinstalled it with the exact same issue occurring after reinstall.

My Deebot is controllable via the Ecovacs app.

### Diagnostics information

[deebot-a707b05238566ee63ae2fddb13538d08-Booth Bot-eeb56b70e4b345b0943348b4337ce3b9.json.txt](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/9791921/deebot-a707b05238566ee63ae2fddb13538d08-Booth.Bot-eeb56b70e4b345b0943348b4337ce3b9.json.txt)

### Anything in the logs that might be useful for us?

```txt
Logger: deebot_client.commands.common
Source: runner.py:119 
First occurred: 7:36:26 PM (6 occurrences) 
Last logged: 7:36:42 PM

Command "getStats" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
Command "getChargeState" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
Command "getCleanInfo" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
Command "getBattery" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
Command "getError" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
```

### Additional information

Recent installation of Zigbee2MQTT & Mosquitto broker.

**Comment by edenhaus** [comment]
`{'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}` this message come directly from the ecovacs server and means normally that there is a communication issue between your bot and the ecovacs server.
But if you are able to control it via the app, there must be something different. Did you update recently your bot?
Did you change some DNS settings?

**Comment by ph0nebooth** [comment]
> `{'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}` this message come directly from the ecovacs server and means normally that there is a communication issue between your bot and the ecovacs server.
> But if you are able to control it via the app, there must be something different. Did you update recently your bot?
> Did you change some DNS settings?

I installed AdGuard but disabled the service during testing and it made no difference.

Strangely enough the integration has started working with no intervention from me. Maybe my IP was blacklisted due to excessive API attempts?
