### ISSUE TITLE
Change active map

### ISSUE THREAD

**Issue by andrea-mattioli** [DeebotUniverse/Deebot-4-Home-Assistant#271]
### Question

hello I have 3 saved maps, I would like to be able to change the active map through custom_command but from the API on the part inherent to the maps I found only the get and a clear not set.
How can I select my active map?

**Comment by edenhaus** [comment]
You can change the map (as ecovacs is describing it) by placing the robot on a different floor and then execute the "setRelocationState" command (This command is exposed as button in HA).

Maybe there exist also other ways to do it, but as ecovacs don't provide any docs about their api and commands, I only know the way above

**Comment by andrea-mattioli** [comment]
Ok thanks
