### ISSUE TITLE
Add support for DE55

### ISSUE THREAD

**Issue by STARTSPr0** [DeebotUniverse/Deebot-4-Home-Assistant#273]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my feature request or idea

### Suggested solution

I own a DE55 vacuum cleaner. The current integration does not work with it, is it possible to add it? I would be very grateful

**Comment by edenhaus** [comment]
I cannot find any information about this model directly on ecovacs. So it's hard for me to identify it your model is newer than the 920/950 or not.
This integration is only supporting newer models as with the 920/950 ecovacs changed the protocol. Supporting older models is hard as I don't have a old model and also I want invest time in a protocol, which soon or later will not be used anymore

**Comment by STARTSPr0** [comment]
This model is old. 
Check this https://market.yandex.ru/product--robot-pylesos-ecovacs-deebot-de55/608397465?cpa=1&nid=83798
I can sniff traffic for u

**Comment by edenhaus** [comment]
Please try this component https://github.com/Ligio/hacc-ozmo.

There will be no support for older models as they use a different protocol
