### ISSUE TITLE
Deebot N8+

### ISSUE THREAD

**Issue by dan-dan81** [DeebotUniverse/Deebot-4-Home-Assistant#275]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

Login to account is correct and the named vacuum is seen.

All entities are added however most are disabled with no data.

Deebot N8+

### Diagnostics information

[deebot-c388b125ccbab53da519aeb639c6a62d-Rosie-343583c935e2a84aaceceecc9e235939.json (1).txt](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/10224953/deebot-c388b125ccbab53da519aeb639c6a62d-Rosie-343583c935e2a84aaceceecc9e235939.json.1.txt)

**Comment by Misunderstood-Wookiee** [comment]
Damn I was about to try adding my N8 will give it a go anyway.

**Comment by edenhaus** [comment]
As specified in the [docs](https://deebot.readthedocs.io/integrations/home-assistant/entities/) you need to enable the entities you need. The will be disabled by default to don't use resource if they aren't needed.
Do you have a specific problem?

**Comment by dan-dan81** [comment]
My bad, I've enabled the entities and all looks to be working.
