### ISSUE TITLE
Time Cleaning and Surface ?

### ISSUE THREAD

**Issue by JeedHome44** [DeebotUniverse/Deebot-4-Home-Assistant#280]
### Question

Hello
Can we have the time cleaning and the surface in information?
Thank you

**Comment by edenhaus** [comment]
Have you enabled the stats sensors? https://deebot.readthedocs.io/integrations/home-assistant/entities/

The should give you the time and the cleaning area

**Comment by JeedHome44** [comment]
i don't find where enable stats sensors ?

**Comment by JeedHome44** [comment]
sorry i find it and i activate it :) thank you so much
