### ISSUE TITLE
Getting temporary ban from deebot

### ISSUE THREAD

**Issue by jdrozdnovak** [DeebotUniverse/Deebot-4-Home-Assistant#285]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed/try to install the latest version

### The problem

If from whatever reason, the robot/wifi became unavailable. The integration will probably ask too many times the deebot API. This leads temporal ban of my home API. I can't even control the vacuum trough the app.
Only solution is disable the integration for few hours. 
Is there some limiting on how many times the deebot can ask? 
I was asking support as well, but they didn't share the numbers

### On which deebot vacuum you have the issue?

N8+

### Which version of the Deebot component are you using?

1.5.0

### Which version of Home Assistant are you using?

2022.12.*

### What type of installation are you running?

Home Assistant OS

### Country

SE

### Instance type

Cloud

### Anything in the logs that might be useful for us?

```txt
Didn't find anything.
```

### Additional information

I do have all the disabled entities enabled. 
Will try to disable them meanwhile

**Comment by edenhaus** [comment]
> Is there some limiting on how many times the deebot can ask?
> I was asking support as well, but they didn't share the numbers

If the support is not sharing this number, I can only guess...

The integration is checking each minute to identify if the robot is available.
If the robot was unavailable and comes back online then the integration needs to poll all data. After this initial pull all changes will be processed via mqtt on one connection.

> I do have all the disabled entities enabled.

Only enable entities, which you need as each entity creates requests.

How was the availability of your robot before the ban?
Are you using the app together with this integration?
Do you use any automation to reload this integration?

**Comment by jdrozdnovak** [comment]
> Only enable entities, which you need as each entity creates requests.

exactly. So far so good. But I didn't got any weird glitch yet. Of course, now that I am trying to replicate it I can't

> How was the availability of your robot before the ban? 

Never any issue. It is really just affected after the robot looses connection for a while.

> Are you using the app together with this integration?

yeah, emptying dust bin and other things.

> Do you use any automation to reload this integration?

nope. 

I am trying to troubleshoot further.

**Comment by edenhaus** [comment]
Please try to.investigate it further.
Also please enable debug logs so all requests will be logged. Maybe ecovacs is sending some sort of warning in the request before banning you.
If yes, I could add some delay for additional requests, when we are close to a ban

**Comment by elykrk** [comment]
I might be having a similar issue. I noticed this seems to happen after restarting HA 1-2x which I believe is causing multiple API calls resulting in a temp ban. I resolve this by power cycling the robot and then reloading the integration. I will see if I can trigger this and upload the debug logs when it happens.
