### ISSUE TITLE
Mop attached sensor Is always off after chaging the water amount

### ISSUE THREAD

**Issue by martiesim** [DeebotUniverse/Deebot-4-Home-Assistant#302]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

The sensor telling me whether the mop is attached doesn't display the correct state. It seems to reset to "off" after a cleaning is done and the robot tries to return to the dock. In my setup I intercept that and send the robot to the next room, but the sensor remains "off" even though the robot still has the mop attached.

### Diagnostics information

[deebot-73ab2d9bfb8bb77ff976364d47ce18a8-Staubi-ac06dff507fb0d7e0bad7329cb4d5a89.json.txt](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/10700596/deebot-73ab2d9bfb8bb77ff976364d47ce18a8-Staubi-ac06dff507fb0d7e0bad7329cb4d5a89.json.txt)

### Anything in the logs that might be useful for us?

```txt
Nothing so far
```

### Additional information

pausing the (subsequent) cleaning, de- and reattaching the mop makes the sensor show the correct value... But I don't want to follow my robot around to do that ;)

**Comment by Nanganator** [comment]
I have noticed this behaviour also. The mop detection used to function faultlessly but has since stopped working. Possibly related to the upgrade between 2022.12 and 2023.01

**Comment by edenhaus** [comment]
Is the mop detected correctly in the app?

**Comment by martiesim** [comment]
The app shows the water waves at the bottom of the header, so I guess yes. Is there a menu where it says it explicitly?

**Comment by martiesim** [comment]
The issue persists, sadly :(

This is tagged needs-more-information. What do you need? I'm willing to provide info where possible. I might need instructions on how to obtain them, though.

**Comment by Nanganator** [comment]
Was a red herring on my side. A full reboot of the Hass VM and host resolved the issues for me.
I’m on:
Home Assistant 2023.1.7
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230110.0 - latest

**Comment by edenhaus** [comment]
@martiesim Can you please try the following steps and please give me feedback?

Prepare:
- enable [debug logs](https://deebot.readthedocs.io/integrations/home-assistant/issues/)
- disconnect the mop from the bot
- verify that in HA and in the app the mop is not shown as attached. Use `deebot.refresh` for HA if required

It's important that you leave the app open on a view, where you can see if the mop is attached. Ecovacs views differ from model...

Step:
- Attach mop
- Check if you see it attached on both. It takes up to ca one minute, so wait a little bit if you don't see it instantly.
- Ensure mop is identified as attach by reopening app or call refresh service on HA
- Dettach mop
-  Check if you see it dettached on both. It takes up to ca 2 minute, so wait a little bit if you don't see it instantly.

Please give me feedback and attach also the logs :)

Also please note that the bot has a "sleeping" mode, which will be activated after some idle time. I think ecovacs implemented it to save battery... When the bot is in this "sleeping" mode, it will not recognize changes (ex. mop is dettached)

Can it be that you dettach the mop, when the bot is in the "sleeping" mode?

**Comment by martiesim** [comment]
Hi @edenhaus,

your last remark hints to a misunderstanding here, so let me clarify and give more details so the attached logs will make more sense:
The sensor shows a wrong value when the robot is done cleaning one room and is sent to the next. I don't touch the robot.

I was always frustrated with the robots handling of doors. E.g.: it's cleaning the hallway. Since it's loud I close the office door to not be disturbed. The robot now sees the door as closed and marks that in it's map. If later I want to clean the office, the robot will drive off it's charging dock, sit there for a second, proclaim that "the area is blocked" and drive back up on the charging dock. I always thought: Why does this stupid thing not drive to the door to see if it's still closed. And now I make it do that manually.

I defined small squares in front of all doors in my flat and when in home assistant I click a button to clean a room, it actually first sends the robot to clean the square in front of the room. During this first clean, the mop sensor correctly shows an attached mop. Now when the robot is done with the square and it's state changes to "returning to base", I send a stop command. If (or when) the door sensor tells me the door is open, I send the robot the command to clean the room. (It may sit there for some time and household members may get a notification to open the door, but if the door is already open, it will clean the room immediately.) I never touched the robot or the mop, but now the mop sensor tells me there's no mop. The ecovacs app however correctly shows that the mop is still attached.

What you might see in the logs is that after home assistant had restarted, I did the routine of attaching and detaching the mop as you described two times. After that I carried the robot in a room where I know "relocating" works and pressed the "clean bathroom" button in home assitant that does the routine described above. My node-red setup is a little flaky at times so this first run failed and I did it again.

The mop sensor worked flawlessly while the robot was set here and I attached and reattached the mop It took at most a few seconds to update and there was no noticable difference in update speed compared to the ecovacs app.
However when I send it to clean the bathroom as described above, the mop sensor showed no mop, even though it was attached. The ecovacs app showed the correct state.

Here's the log file:
[neu 5.txt](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/10882794/neu.5.txt)

as per the warning on the page you linked I searched for "token" and replaced all values I found with "[REMOVED]".

Thank you :)

**Comment by edenhaus** [comment]
Yes indeed I have understood it wrong...

> If (or when) the door sensor tells me the door is open

Do you have a separate door sensor or do you calculate it from the map if the door is open?

I could identify the bug.
Due the design from ecoavcs the water amount and the mop is one command (https://github.com/DeebotUniverse/client.py/blob/7fbf5122061133a1c963a2264e1b56285be2f8cb/deebot_client/commands/water_info.py#L30)
Some time ago I have added the functionality, that the water amount sensor will update, when you change the settings in the app.
As the mop property cannot be changed, the app will not send this property and the default value for a boolean (which i use for the mop) is False.

As you change the water amount, the mop will be set incorrectly to false. I will fix it with the next version, in the meantime you can use the refresh service to request an update of the water sensors.

```yaml
service: deebot.refresh
data:
  part: Water
target:
  device_id: [REMOVED]
```

**Comment by martiesim** [comment]
> Do you have a separate door sensor or do you calculate it from the map if the door is open?

I have homematic IP door sensors on all doors in the flat. The problem with the "area blocked" error was that the robot can't see most doors from it's dock. Even if cleaning the small square in front of the door doesn't update the map (because the door is still closed at this point), sending the robot into the room, when it is sat in front of it works, because now the laser sees the door to be open and it can caluclate a route. That's the root of my frustration here because obviously ecovacs did think of the fact that doors can change state...

I wanted this to overcome my lazyness and have the robot start cleaning automatically. Now it just starts and if a door is closed, notifications are send to nag me and my partner to open the door. I let it sit for a maximum of 30min. If by then no one opened the door, it returns to the dock. (Just in case no one is home so the battery doesn't drain)



> I could identify the bug.

yay :)



> As you change the water amount, the mop will be set incorrectly to false. I will fix it with the next version, in the meantime you can use the refresh service to request an update of the water sensors.

Thank you very much :)
