### ISSUE TITLE
Request for support for Deebot T10 Plus

### ISSUE THREAD

**Issue by rahulpdev** [DeebotUniverse/Deebot-4-Home-Assistant#308]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my feature request or idea

### Suggested solution

I checked the list of supported models on your website and did not see any reference to the T10 Plus. Could this model be added to the set of supported devices please?

**Comment by edenhaus** [comment]
Can you confirm that the T10 Plus is working with this integration?

**Comment by rahulpdev** [comment]
> Can you confirm that the T10 Plus is working with this integration?

@edenhaus there is some functionality that is working. For example, the commands available in the UI for the vacuum entity are all working as expected. However, the clean spot command fails and returns an Unknown error. I also get the same response when I use the send command service and enter `spot_area` as the command

**Comment by rahulpdev** [comment]
@edenhaus does this mean some work needs to be done to fully support the model with the integration

**Comment by edenhaus** [comment]
yes exactly. Feel free to add the missing commands :)

**Comment by rahulpdev** [comment]
> yes exactly. Feel free to add the missing commands :)

@edenhaus That's way beyond my current competency, I'll give it a try but no one reading this should wait for my contribution lol!

**Comment by rahulpdev** [comment]
> yes exactly. Feel free to add the missing commands :)

@edenhaus can you direct me as to how I can add the missing command, what do I need to do?

**Comment by rahulpdev** [comment]
Hello, can someone tell me in more detail what I need to do to progress this request?

**Comment by mrbungle64** [comment]
@rahulpdev 

You need to capture the network traffic of the Ecovacs Home with a [man-in-the-middle proxy](https://mitmproxy.org/) and extract the payload of the commands that are missing or not working correctly.

**Comment by akslow** [comment]
> 

Maybe this helps?
https://github.com/mrbungle64/ecovacs-deebot.js

**Comment by TruantRiccardo** [comment]
I own a t10 plus and an n8 plus, and I notice that the map I get from the t10 is "broken" compared to the map on the n8. Do you also have the same problem?
![image](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/44238224/36501ac9-c650-412a-9576-4517a178b0e7)
