### ISSUE TITLE
DEEBOT X1 OMNI

### ISSUE THREAD

**Issue by wcavanagh** [DeebotUniverse/Deebot-4-Home-Assistant#309]
### Question

Does this support the DEEBOT X1 OMNI, I am having trouble getting anything out of it.  The integration has pulled in the name, so i know it is logging into my account ok.  But I can access any sensors or anything.

### Additional information

restored: true
fan_speed_list: normal, high
friendly_name: VLAD the INHALER
supported_features: 2043

**Comment by edenhaus** [comment]
the X1 should work with this integration. Not all features are supported but the basics should work. Please check out the docs and did you have activated all required sensors?
if you still have a problem, please open a bug issue with all required information. I need this information to help you.

**Comment by wcavanagh** [comment]
I cant find where to activate the sensors.  I have battery level just now.

**Comment by edenhaus** [comment]
See https://deebot.readthedocs.io/integrations/home-assistant/entities/

**Comment by relliky** [comment]
I have euro version of X1 omni from amazon. All the basic stuffs works. I got 23 entities for this robot.
