### ISSUE TITLE
Expose map name to HA

### ISSUE THREAD

**Issue by eXitus01** [DeebotUniverse/Deebot-4-Home-Assistant#310]
### Question

Hi,

I use the advanced display with the custom button cards.
I have my Deebot sometimes on one floor and sometimes on another. Since I can never remember where it is at the moment, I can never be sure to select the right rooms.
Can I query some attribute and display a different button depending on the value?

**Comment by edenhaus** [comment]
It's currently not implemented but it would be possible to return the name and id of the current map.
Would this help?

P.S. Please note that when you move the robot from one floor to the other, you need to call relocate (via app or HA) first before the map would be updated

**Comment by eXitus01** [comment]
The name would help a lot. Is it already possible to get the name of the floor? If yes can you show an example how to get it?

**Comment by edenhaus** [comment]
It is possible via a custom command event, where you call the following command https://deebot.readthedocs.io/advanced/data_types/json/commands/map/#getcachedmapinfo

Please read the docs carefully as it is an advanced topic
