### ISSUE TITLE
Deebot slim 2 not compatible

### ISSUE THREAD

**Issue by Femafe** [DeebotUniverse/Deebot-4-Home-Assistant#316]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed/try to install the latest version

### The problem

![Screenshot 2023-03-06 123909](https://user-images.githubusercontent.com/127099255/223103480-d7676436-a0a2-4e08-abb9-4f071b8cafd2.png)
I tried to login to deebot 4 home with my deebot email and password and wehn i did this this message pops uo even tho in this table https://deebot.readthedocs.io/home/models/ deebot slim 2 is supportet for deebot 4 home

### On which deebot vacuum you have the issue?

Deebot slim 2

### Which version of the Deebot component are you using?

1.5.0

### Which version of Home Assistant are you using?

2023.3.1

### What type of installation are you running?

Home Assistant OS

### Country

de

### Continent

eu

### Instance type

None

**Comment by mrbungle64** [comment]
@Femafe 

> even tho in this table https://deebot.readthedocs.io/home/models/ deebot slim 2 is supportet for deebot 4 home

This is not correct. Please take another look at it:

![D4HA models 2023-03-06 13 54 33](https://user-images.githubusercontent.com/37313763/223116323-5ab53c45-16e5-4206-adef-89c1349d8abc.png)

**Comment by mrbungle64** [comment]
@Femafe 

The Deebot Slim 2 should work with the official "Ecovacs" integration.

**Comment by Femafe** [comment]
ok thanks for your fast response
