### ISSUE TITLE
Deebot not updating. 

### ISSUE THREAD

**Issue by peteypauls** [DeebotUniverse/Deebot-4-Home-Assistant#326]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

When I leave my home, Deebot N8+ starts and returns to the dock when I come home.  This has been happening randomly for a while, but when I get home it is still vacuuming and I noticed it still shows as docked in home assistant.  so basically it's not updating to cleaning sometimes when it starts.  I have to reload the integration and then it is fine.  

The last time it ran was March 26th and I found the two errors below in the log.

### Diagnostics information

This error originated from a custom integration.

Logger: custom_components.deebot.hub
Source: custom_components/deebot/hub.py:114 
Integration: Deebot 4 Home Assistant (documentation, issues) 
First occurred: March 22, 2023, 9:34:56 PM (2 occurrences) 
Last logged: March 26, 2023, 7:23:25 PM

failure (3002) on getting devices
Traceback (most recent call last):
  File "/config/custom_components/deebot/hub.py", line 104, in _check_status_task
    await self._check_status_function()
  File "/config/custom_components/deebot/hub.py", line 114, in _check_status_function
    devices = await self._api_client.get_devices()
  File "/usr/local/lib/python3.10/site-packages/deebot_client/api_client.py", line 61, in get_devices
    raise ApiError(
deebot_client.exceptions.ApiError: failure  (3002) on getting devices

This error originated from a custom integration.

Logger: deebot_client.api_client
Source: custom_components/deebot/hub.py:114 
Integration: Deebot 4 Home Assistant (documentation, issues) 
First occurred: March 22, 2023, 9:34:56 PM (2 occurrences) 
Last logged: March 26, 2023, 7:23:25 PM

Failed to get devices: {'todo': 'result', 'ret': 'fail', 'errno': 3002, 'code': 3002}

**Comment by edenhaus** [comment]
Can you reproduce the issue?

**Comment by peteypauls** [comment]
I’m not sure how I would actually do that. It is random and I supplied the logs of the last activity before the most recent event occurred.

**Comment by edenhaus** [comment]
It's probably #293, which is hopefully fixed in the next version. Which will come hopefully the next week (beta)
If the issue still exist please activate debug logs and attach them to the issue
