### ISSUE TITLE
T8 Aivi only launches in vacuuming mode instead of mopping mode

### ISSUE THREAD

**Issue by IrealiTY** [DeebotUniverse/Deebot-4-Home-Assistant#327]
### Question

I'm not sure if I maybe do something wrong but when I launch the vacuum via HA it always only launches in vacuuming mode instead of scrubbing mode.
If I launch it via the ecovacs app it works correctly, I kind of thought it would be the same command.

**Comment by mrbungle64** [comment]
@IrealiTY 

> I kind of thought it would be the same command.

Correct. It's the same command.

Are you sure that the mopping system is installed correctly?

**Comment by IrealiTY** [comment]
Yep, because I paused it with the App (after it was launched via HA) and restarted it with the app and it started using the Mopping attachment

**Comment by mrbungle64** [comment]
@IrealiTY 

You are using the OZMO Pro mopping system (the Scrubbing function), right?

**Comment by IrealiTY** [comment]
> @IrealiTY
> 
> You are using the OZMO Pro mopping system (the Scrubbing function), right?

Correct, yeah

**Comment by mrbungle64** [comment]
@IrealiTY 

Is it really reproducible?

You can set the scrubbing type via API (quick and deep scrubbing), but as far as I know there's no option to start cleaning without scrubbing (if OZMO Pro is installed).

**Comment by IrealiTY** [comment]
I noticed it twice so far, I'll keep an eye on it.

**Comment by IrealiTY** [comment]
Couldn't verify the issue for now again, will keep an eye on it and will try to properly report.
