### ISSUE TITLE
After HA 2023.4 update, this state is not translated.

### ISSUE THREAD

**Issue by limitless00net** [DeebotUniverse/Deebot-4-Home-Assistant#335]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

After HA 2023.4 update, This state is not translated. it is only in English.
This is caused by changes in HA frontend: https://github.com/home-assistant/frontend/pull/15820/files

### Diagnostics information

[deebot-Robot Vacuum.txt](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/11283515/deebot-Robot.Vacuum.txt)

### Additional information

![20230420_186](https://user-images.githubusercontent.com/64896798/233291708-fd6e2443-5767-4e27-88b7-3a3487059cd1.png)

**Comment by edenhaus** [comment]
This issue is not related to deebot but to the vacuum component of HA. If you want to get the states translated in your language please have a look at https://developers.home-assistant.io/docs/translations and help HA to translate it in your language.
