### ISSUE TITLE
No option to use Bumper during configuration

### ISSUE THREAD

**Issue by jspayd** [DeebotUniverse/Deebot-4-Home-Assistant#336]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed/try to install the latest version

### The problem

When adding the Deebot 4 Home Assistant integration to Home Assistant, there is no option to use Bumper. The first configuration page I see asks for "E-mail or ShortId", "Password", etc.

This may be because my Bumper instance is running on a different machine on my local network from my Home Assistant instance, however, I have confirmed that bumper is running and that my vacuum is connected to it.

### On which deebot vacuum you have the issue?

Deebot Ozmo T8

### Which version of the Deebot component are you using?

I cannot get far enough in the setup process to see this

### Which version of Home Assistant are you using?

2023.4.5

### What type of installation are you running?

Home Assistant OS

### Country

it

### Continent

eu

### Instance type

Bumper

**Comment by edenhaus** [comment]
I can confirm that you it is working with bumper (if you have setup the dns resolver to point to your bumper instance).

Also you need to enable the "Advanced Mode" in your profile settings in your HA instance.
![image](https://user-images.githubusercontent.com/26537646/233793265-adf0c52d-6927-4051-a93d-0588448f4f9f.png)

After enabling start again the config flow setup and you can select bumper

**Comment by jspayd** [comment]
Thanks, I was not aware of advanced mode. I have the Bumper option after enabling it.
