### ISSUE TITLE
Support Goat G1

### ISSUE THREAD

**Issue by lal12** [DeebotUniverse/Deebot-4-Home-Assistant#341]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my feature request or idea

### Is your feature request related to a problem?

The Goat G1 is a new camera AI based robot mower from Ecovacs. I just got one and while the integration for it mostly works it isn't a vacuum so most stats aren't available and probably many that are available aren't shown.

### Suggested solution

Integrate Goat G1 support.

### Alternatives you've considered

I am not sure if this library is the correct place/scope for this, since it specifically is targeted to Deebot.

### Additional information

Would be happy to help debug/implement it.

![image](https://user-images.githubusercontent.com/14139770/235328974-e5d002b8-41cc-466f-8472-8e459538d754.png)

![image](https://user-images.githubusercontent.com/14139770/235328998-9a6d5c3d-743f-4878-88ca-d9f010aacd38.png)

**Comment by edenhaus** [comment]
Please refer to https://github.com/DeebotUniverse/client.py/discussions/244
You need to analyse the traffic and find out the new commands.

I cannot afford to buy it on my own and I also have no support from ecovacs. If you don't have the technical skills to analyse the traffic, maybe you can buy me some [beers](https://www.buymeacoffee.com/edenhaus) or buy for me the G1 :heart_eyes:

**Comment by dogmatic69** [comment]
I can do it, is there some information how to extract the traffic?

**Comment by JeedHome44** [comment]
Hello,

I can help you ! I just add my Goat G1 in this integration and I have that:

![image](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/41892950/e9f29bae-82a5-4de9-b80a-bb807d45f30b)

Can you explain me how can I analyse traffic and I will do it. 

Sorry for my bad English, I'm French.

**Comment by JeedHome44** [comment]
My bot Goat G1 work perfectly now.
What I have to do to send you files to integrate it ?

![image](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/41892950/45d51437-a64a-4893-9757-046b180f5407)

**Comment by JeedHome44** [comment]
personne ne peut me dire comment analyser le traffic ?

**Comment by edenhaus** [comment]
@JeedHome44 Please write in English, I don't understand French.

**Comment by JeedHome44** [comment]
Nobody can say me how to captur my Goat G1 to send you results ?
