### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 294: invalid start byte

### ISSUE THREAD

**Issue by limitless00net** [DeebotUniverse/Deebot-4-Home-Assistant#344]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

The following error codes occur repeatedly while using Deebot.

Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:137
First occurred: 10:19:20 (8 occurrences)
Last logged: 10:21:45

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/deebot_client/mqtt_client.py", line 59, in _on_message
    _LOGGER.debug("Got message: topic=%s; payload=%s;", topic, payload.decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 294: invalid start byte

### Diagnostics information

[deebot-Robot Vacuum.json.txt](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/11392324/deebot-Robot.Vacuum.json.txt)

**Comment by edenhaus** [comment]
Can you please activate debug logs and attach them here with the error

**Comment by limitless00net** [comment]
Here it is.
[home-assistant_deebot_2023-05-07T14-13-34.876Z.zip](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/11415181/home-assistant_deebot_2023-05-07T14-13-34.876Z.zip)

**Comment by edenhaus** [comment]
You have a really strange `"cleanId":"0\\u0015\xb7\xd2\x7f"`...

Will fix it probably on the weekend or next week

**Comment by edenhaus** [comment]
It is fixed in the library and the fix will be included in the next (beta) version
