### ISSUE TITLE
Migration with edge case configuration

### ISSUE THREAD

**Issue by Edo78** [DeebotUniverse/Deebot-4-Home-Assistant#35]
### Question

Hi, before proceding to the migration I've read ALL the migration guide but I have a question.

My actual configuration has 2 account, a chinese one and an italian one.
This new repository still supports multiple account and chinese ones?

I have to ask ... bettere safe than sorry ;)

**Comment by edenhaus** [comment]
Yes

Actual it's a fork of the old component. I will only continue the development here.
