### ISSUE TITLE
x1 omni: Error

### ISSUE THREAD

**Issue by ankycooper** [DeebotUniverse/Deebot-4-Home-Assistant#353]
I'm able to add the robot however, the status has error
and a lot of sensors like live map are unavailable.

country code au
continent code ww

Following is in the logs

```
Logger: deebot_client.commands.common
Source: runner.py:179
First occurred: May 23, 2023 at 11:40:21 PM (12 occurrences)
Last logged: 12:49:28 AM

Command "getMapSubSet" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
```

**Comment by edenhaus** [comment]
`'wait for response timed out'` means that the ecovacs server was not able to communicate in time with your bot. Please verify that your bot has a stable internet connection.

Have you activated the sensor as described in https://deebot.readthedocs.io/integrations/home-assistant/entities/?
