### ISSUE TITLE
X1 Omni issue

### ISSUE THREAD

**Issue by paolomorabito** [DeebotUniverse/Deebot-4-Home-Assistant#354]
I installed the integration and everything works fine.
However, I encountered some issue:

1. "Last cleaning" sensor does not work. It is always in UNKNOWN state
2. "deebot_cleaning_job" service seems not to work. I would use it to find coordinates of some rooms. Anyway I found coordinates using logs.

Thanks

**Comment by edenhaus** [comment]
Sorry complete overlooked your issue. Do you still have the described issue?
