### ISSUE TITLE
After 1.6.0b2 update, very frequent 'unknown' state

### ISSUE THREAD

**Issue by limitless00net** [DeebotUniverse/Deebot-4-Home-Assistant#355]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

After 1.6.0b2 update, the state of the robot vacuum cleaner (vacuum.robot_vacuum) changes to an 'unknown' state every few seconds.

![20230526_188](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/64896798/8fa23bad-cbf4-4ed2-8b85-8878a868259a)

For your understanding, I translated the Korean of the screenshot.

로봇 청소기: device name of the vacuum
알게 없게 됨 : unknown
청소 중으(로) 변경되었습니다 : changed to 'cleaning'

Attached debug logs
[home-assistant_deebot_2023-05-26T01-10-30.071Z.log](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/11570605/home-assistant_deebot_2023-05-26T01-10-30.071Z.log)

### Diagnostics information

[deebot-vacuum.json.txt](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/11570518/deebot-vacuum.json.txt)

**Comment by edenhaus** [comment]
Thanks for reporting. Will be solved with the next beta too.

**Comment by edenhaus** [comment]
Should be fixed in beta3, if not please reopen the issue again :)
