### ISSUE TITLE
ErrorEvent in new integration 

### ISSUE THREAD

**Issue by serlinGi** [DeebotUniverse/Deebot-4-Home-Assistant#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

Hi,
thank you for this new integration development!!!
I installed immediately :)
I made the transition to new integration following the notes; so, so, I've removed old versionand reinstalled everything.
I have updated my cards with the new sensor names.
I've 2 robots integrated with the same account and when I restart HomeAssistant I find myself reporting an error in the log
.....
I'll place the error in my log when HA restarted,
I also add that the "sensor.RBTNAME_last_cleaning"  is in an unknown state.
THX and good life

### On which deebot vacuum you have the issue?

Deebot Ozmo T8 & Deebot Ozmo T8 Aivi

### Which version of the Deebot component are you using?

0.1.1

### Which version of Home Assistant are you using?

2021.11.3

### What type of installation are you running?

Home Assistant OS

### Country

IT

### Continent

EU

### Instance type

Cloud

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant
Source: custom_components/deebot/sensor.py:257
Integration: Deebot 4 Home Assistant (documentation, issues)
First occurred: 2:09:54 AM (2 occurrences)
Last logged: 2:09:54 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/deebot/sensor.py", line 257, in on_event
    if event.logs:
AttributeError: 'ErrorEvent' object has no attribute 'logs'
```

### Additional information

My sistem:
Version | core-2021.11.3
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.7
Operating System Family | Linux
Operating System Version | 5.10.17-v8
CPU Architecture | aarch64

**Comment by edenhaus** [comment]
Can you please install the main version (beta) and check if the issue is solved?

**Comment by serlinGi** [comment]
sorry, now I'm at work, I can try it in about 4 hours.
ok for you?
