### ISSUE TITLE
Deebot loses connection and not resume it

### ISSUE THREAD

**Issue by belangp** [DeebotUniverse/Deebot-4-Home-Assistant#361]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

At random times, the status of Deebot stops updating in HA and it's sometimes impossible to control the vacuum. This seems to always happen after this message in the logs:

A client error occurred, probably the ecovacs servers are unstable: Cannot connect to host portal-ww.ecouser.net:443 ssl:True [Try again]

After that, the only way to resume is to reload the integration, which only works for a little while before stopping again.

### Diagnostics information

[deebot-494cd0b46094a52c710675bdf177b2b0-Alfred-d3b20248ca523dadbc844381d5ec0e64.json.txt](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/11668544/deebot-494cd0b46094a52c710675bdf177b2b0-Alfred-d3b20248ca523dadbc844381d5ec0e64.json.txt)

**Comment by edenhaus** [comment]
Please update to the new version `1.6.0`, which has some stability improvements. If the issue still exists please open a new issue
