### ISSUE TITLE
Version 1.6.0 is not compatible with Windows

### ISSUE THREAD

**Issue by StefanoGiugliano** [DeebotUniverse/Deebot-4-Home-Assistant#364]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

Since I upgraded to version 1.6.0 (from 1.5.0) this problem started to popup

### Diagnostics information

HA 2013.6.0

### Anything in the logs that might be useful for us?

```txt
At the startup I got the following error:

2023-06-08 15:15:57.716 ERROR (MainThread) [deebot_client.mqtt_client] An exception occurred
Traceback (most recent call last):
  File "XXXXX.homeassistant\deps\Python311\site-packages\deebot_client\mqtt_client.py", line 158, in mqtt
    async with (await self._get_client()) as client:
  File "XXXXX.homeassistant\deps\Python311\site-packages\asyncio_mqtt\client.py", line 822, in __aenter__
    await self.connect()
  File "XXXXX.homeassistant\deps\Python311\site-packages\asyncio_mqtt\client.py", line 373, in connect
    await loop.run_in_executor(
  File "XXXXXPython311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "XXXXXPython311\Lib\site-packages\paho\mqtt\client.py", line 914, in connect
    return self.reconnect()
           ^^^^^^^^^^^^^^^^
  File "XXXXXPython311\Lib\site-packages\paho\mqtt\client.py", line 1086, in reconnect
    self._call_socket_open()
  File "XXXXXPython311\Lib\site-packages\paho\mqtt\client.py", line 2155, in _call_socket_open
    on_socket_open(self, self._userdata, self._sock)
  File "XXXXX.homeassistant\deps\Python311\site-packages\asyncio_mqtt\client.py", line 778, in _on_socket_open
    self._loop.add_reader(sock.fileno(), callback)
  File "XXXXXPython311\Lib\asyncio\events.py", line 530, in add_reader
    raise NotImplementedError
NotImplementedError
2023-06-08 15:16:03.680 ERROR (MainThread) [mqtt] Caught exception in on_socket_close:
```

**Comment by edenhaus** [comment]
Please add the diagnostic information, found under Settings -> Integrations -> Deebot 4 Home Assistant -> Device
See also https://www.home-assistant.io/integrations/diagnostics/

**Comment by StefanoGiugliano** [comment]
[deebot.txt](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/11702642/deebot.txt)

Attached

**Comment by edenhaus** [comment]
The underlaying mqtt library has a problem with windows… Have you installed HA directly on windows?

**Comment by StefanoGiugliano** [comment]
Yes

**Comment by edenhaus** [comment]
Can you please share more information about your installation?

Reading through https://www.home-assistant.io/installation/windows, either you should use a virtual box with Linux or Windows Subsystem for Linux (WSL).

**Comment by StefanoGiugliano** [comment]
I use Windows native and Python 3.11. No WSL, no Virtual Box...

**Comment by edenhaus** [comment]
After checking on https://github.com/home-assistant/architecture/blob/master/adr/0016-home-assistant-core.md#supported-operating-systems-and-versions and https://github.com/home-assistant/architecture/blob/master/adr/0012-define-supported-installation-method.md I decided to **not** spent time to fix this issue. HA is not supporting native windows installation without WSL and so also this integration.

You can try if the workaround specified in the lib will help you https://github.com/sbtinstruments/aiomqtt#note-for-windows-users

**Comment by StefanoGiugliano** [comment]
How can I apply this workaround?

**Comment by edenhaus** [comment]
Quote from https://github.com/home-assistant/architecture/blob/master/adr/0012-define-supported-installation-method.md
> The Home Assistant team will not prevent you from running Home Assistant using an unofficial method. However, we cannot help with issues that you encounter.

I have no idea if and how the workaround is applied. Also I have no idea, which side effects/issue it will introduce.
You need to find a solution yourself, as I even have no windows system around.

PS: I would suggest you to switch to a supported HA installation.
