### ISSUE TITLE
Support DEEBOT T20 OMNI

### ISSUE THREAD

**Issue by chinswain** [DeebotUniverse/Deebot-4-Home-Assistant#369]
### Question

I've just had a DEEBOT T20 OMNI delivered and connected up to home assistant, is it possible to support this model?
So far it seems to be good, other than the live map, there is no camera entity added.

Happy to gather info and test if required.

**Comment by edenhaus** [comment]
Hi with you help we can add support for your model.
I currently only have the 950 and this model doesn't have a camera. To add support for the camera, you need to analyze the traffic and find out which commands and co is missing.
Unfortunately you need to do that as my robot is not supporting this advanced feature and you shouldn't give a stranger access to your robot

**Comment by chinswain** [comment]
Do you have any documentation on how to capture the data needed?

**Comment by edenhaus** [comment]
You can use the maninthemiddleproxy to capture the traffic. Please refer to their docs on how to setup. Afterwards you need to analyse the missing commands 😊
Feel free to reach out for help

**Comment by JeedHome44** [comment]
i just buy one T20 too. if i can help you to add it !
i have before a X1 Omni and it's word but i have this error now !

Cendrillon = Ecovacs T20
Bambi = Goat G1

I need to have this two but in my HA. If you say me how help you.

Sorry for my bad English. I'm French !

![image](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/41892950/8e6ebf36-2dab-4ea7-80b4-5f8db801e3bd)

**Comment by JeedHome44** [comment]
Nobody can say me how to captur my T20 to send you results ?

**Comment by NEVdataDyne** [comment]
Avoir support of the T20 omni, see issue DeebotUniverse/client.py#441
About the camera,I don't think this a feature supported by ecovacs

**Comment by edenhaus** [comment]
Closing it in favor of DeebotUniverse/client.py#441
