### ISSUE TITLE
Could not execute command getBattery

### ISSUE THREAD

**Issue by harphere** [DeebotUniverse/Deebot-4-Home-Assistant#373]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

I have a T8 vacuum and am running the latest integration. I've not had a successful run/connection since updating to 1.6.0. Lovelace shows my vacuum in Error state and the logs have two Warnings:
1)
```
Logger: deebot_client.command
Source: /usr/local/lib/python3.11/site-packages/deebot_client/command.py:79
First occurred: 2:12:58 PM (3 occurrences)
Last logged: 9:16:27 PM

Could not execute command getBattery
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 867, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/deebot_client/command.py", line 62, in execute
    result = await self._execute(authenticator, device_info, event_bus)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/deebot_client/command.py", line 90, in _execute
    response = await self._execute_api_request(authenticator, device_info)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/deebot_client/command.py", line 143, in _execute_api_request
    return await authenticator.post_authenticated(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/deebot_client/authentication.py", line 361, in post_authenticated
    return await self._auth_client.post(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/deebot_client/authentication.py", line 247, in post
    async with self._config.session.post(
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host portal-ww.ecouser.net:443 ssl:True [Try again]
```

2)
```
Logger: deebot_client.commands.common
Source: runner.py:179
First occurred: 12:16:40 PM (4 occurrences)
Last logged: 12:20:11 PM

No response received for command "getMapSubSet". This can happen if the vacuum has network issues or does not support the command
No response received for command "getStats". This can happen if the vacuum has network issues or does not support the command
No response received for command "getPos". This can happen if the vacuum has network issues or does not support the command
No response received for command "getBattery". This can happen if the vacuum has network issues or does not support the command
```
`
I can operate the vacuum just fine from the Android app.
I have the integration configured with CA country and NA continent.

### Diagnostics information

[deebot-a311e8dbc7dc99a52c5db52a42e7f1d6-Scrappy-8c589775ae5d24eb996d36897e55a013.json.txt](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/11889498/deebot-a311e8dbc7dc99a52c5db52a42e7f1d6-Scrappy-8c589775ae5d24eb996d36897e55a013.json.txt)

### Anything in the logs that might be useful for us?

```txt
See "The problem"
```

### Additional information

See "The problem"

**Comment by edenhaus** [comment]
From the diagnostic information, you have set the country to `WW` and not to `NA` as written above. Try to change it to `NA`

Did this fix your issue?

**Comment by limitless00net** [comment]
same here.

**Comment by edenhaus** [comment]
@limitless00net Please provide logs with more details

**Comment by limitless00net** [comment]
> Please provide logs with more details

Please see the logs and the diagnostic information.

Logger: deebot_client.commands.common
Source: runner.py:179
First occurred: 오전 11:45:19 (8 occurrences)
Last logged: 오전 11:51:20

No response received for command "getMapSubSet". This can happen if the vacuum has network issues or does not support the command
No response received for command "getLifeSpan". This can happen if the vacuum has network issues or does not support the command
No response received for command "getChargeState". This can happen if the vacuum has network issues or does not support the command
No response received for command "getCleanInfo". This can happen if the vacuum has network issues or does not support the command

[home-assistant_deebot_2023-07-10T02-56-02.031Z.log](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/11997418/home-assistant_deebot_2023-07-10T02-56-02.031Z.log)

**Comment by harphere** [comment]
> From the diagnostic information, you have set the country to `WW` and not to `NA` as written above. Try to change it to `NA`
> 
> Did this fix your issue?

I re-added the integration this morning with CA country (Canada) and NA continent but the State is still 'unavailable'. 
The HA logs:
```
This error originated from a custom integration.

Logger: mqtt
Source: custom_components/deebot/hub.py:12
Integration: Deebot 4 Home Assistant (documentation, issues)
First occurred: 11:54:15 AM (1 occurrences)
Last logged: 11:54:15 AM

We renamed asyncio-mqtt to aiomqtt and released a version 1.0.0 in the process. This is the last release under the asyncio-mqtt name. You can find the new repository at https://github.com/sbtinstruments/aiomqtt
```
The diagnostics:
[deebot-663989ca7466147c2f088c4ea3e449be-Scrappy-8c589775ae5d24eb996d36897e55a013.json.txt](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/12004986/deebot-663989ca7466147c2f088c4ea3e449be-Scrappy-8c589775ae5d24eb996d36897e55a013.json.txt)

**Comment by neildsb** [comment]
+1

Home Assistant 2023.7.1
Supervisor 2023.07.1
Operating System 10.3
Frontend 20230705.1 - latest

Logger: deebot_client.commands.common
Source: runner.py:179
First occurred: 10 July 2023 at 9:33:13 pm (715 occurrences)
Last logged: 9:57:24 am

No response received for command "getBattery". This can happen if the vacuum has network issues or does not support the command
No response received for command "getSpeed". This can happen if the vacuum has network issues or does not support the command
No response received for command "getCachedMapInfo". This can happen if the vacuum has network issues or does not support the command
No response received for command "getChargeState". This can happen if the vacuum has network issues or does not support the command
No response received for command "getCleanInfo". This can happen if the vacuum has network issues or does not support the command

**Comment by edenhaus** [comment]
For everybody: Without logs I cannot help you and I need debug logs not only "No response received for command "getCleanInfo". This can happen if the vacuum has network issues or does not support the command". So please activate debug logs and send attach them here.

@nickelnine `Cannot connect to host portal-ww.ecouser.net:443` means your instance is not able to connect to the ecovacs server. So please check that your instance has a stable internet connection

**Comment by harphere** [comment]
> For everybody: Without logs I cannot help you and I need debug logs not only "No response received for command "getCleanInfo". This can happen if the vacuum has network issues or does not support the command". So please activate debug logs and send attach them here.
> 
> @nickelnine `Cannot connect to host portal-ww.ecouser.net:443` means your instance is not able to connect to the ecovacs server. So please check that your instance has a stable internet connection

Yes, I got mine working eventually by realizing the app was not connecting. All is good now for me. Thanks for the awesome work here.
