### ISSUE TITLE
renamed asyncio-mqtt

### ISSUE THREAD

**Issue by neildsb** [DeebotUniverse/Deebot-4-Home-Assistant#374]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

This error originated from a custom integration.

Logger: mqtt
Source: custom_components/deebot/hub.py:12
Integration: Deebot 4 Home Assistant (documentation, issues)
First occurred: 8:27:31 am (1 occurrences)
Last logged: 8:27:31 am

We renamed asyncio-mqtt to aiomqtt and released a version 1.0.0 in the process. This is the last release under the asyncio-mqtt name. You can find the new repository at https://github.com/sbtinstruments/aiomqtt

### Diagnostics information

Home Assistant 2023.7.0
Supervisor 2023.07.1
Operating System 10.3
Frontend 20230705.0 - latest

**Comment by edenhaus** [comment]
Will release probably today/tomorrow a fix

**Comment by geofffarmer** [comment]
I'm still seeing this error message in my logs yet I think I'm running the latest version (1.6.1) of your software. Am I doing something wrong?

**Comment by neildsb** [comment]
still a problem with 1.6.1 :-(

Home Assistant 2023.7.1
Supervisor 2023.07.1
Operating System 10.3
Frontend 20230705.1 - latest


This error originated from a custom integration.

Logger: mqtt
Source: custom_components/deebot/hub.py:12
Integration: Deebot 4 Home Assistant (documentation, issues)
First occurred: 10 July 2023 at 9:32:56 pm (1 occurrences)
Last logged: 10 July 2023 at 9:32:56 pm

We renamed asyncio-mqtt to aiomqtt and released a version 1.0.0 in the process. This is the last release under the asyncio-mqtt name. You can find the new repository at https://github.com/sbtinstruments/aiomqtt
