### ISSUE TITLE
Entity None xxx is implicitly using device name by not setting its name. Instead

### ISSUE THREAD

**Issue by neildsb** [DeebotUniverse/Deebot-4-Home-Assistant#375]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:365
First occurred: 11:06:03 pm (52 occurrences)
Last logged: 11:06:03 pm

Entity None (<class 'custom_components.deebot.sensor.LastCleaningJobSensor'>) is implicitly using device name by not setting its name. Instead, the name should be set to None, please report it to the custom integration author.
Entity None (<class 'custom_components.deebot.sensor.LastErrorSensor'>) is implicitly using device name by not setting its name. Instead, the name should be set to None, please report it to the custom integration author.
Entity None (<class 'custom_components.deebot.sensor.DeebotGenericSensor'>) is implicitly using device name by not setting its name. Instead, the name should be set to None, please report it to the custom integration author.
Entity None (<class 'custom_components.deebot.switch.DeebotSwitchEntity'>) is implicitly using device name by not setting its name. Instead, the name should be set to None, please report it to the custom integration author.
Entity None (<class 'custom_components.deebot.vacuum.DeebotVacuum'>) is implicitly using device name by not setting its name. Instead, the name should be set to None, please report it to the custom integration author.

### Diagnostics information

Home Assistant 2023.7.1
Supervisor 2023.07.1
Operating System 10.3
Frontend 20230705.1 - latest

**Comment by rwez** [comment]
+1 
I have exactly the same problem.
