### ISSUE TITLE
Floor information?

### ISSUE THREAD

**Issue by gazpachoking** [DeebotUniverse/Deebot-4-Home-Assistant#38]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my feature request or idea

### Is your feature request related to a problem?

It would be nice to be able to see floor (map name) information for a couple situations:
- The current floor of the robot
- The floor the last cleaning occurred on

### Suggested solution

Add attributes to both the vacuum entity, as well as the last_cleaning entity.

### Additional information

Not sure if this info is available via the api, but I'm hoping so!

**Comment by gazpachoking** [comment]
It would be awesome if the current area could be added as an attribute. 👍 I could store the last cleaned area pretty easily then with an automation triggered on a cleaning finished event or something.

**Comment by edenhaus** [comment]
Now thinking about this again, I need to say that further analyse is required. We can poll the name of the map, but we need to analyse it if the robot send out a message on `atr`-channel, when the map has changed. I avoid to implement a polling on a specific interval as moving the bot to another floor is and will be a manual action by the user.

Sorry but I have to say, that this feature has a low priority for me as I have only a single floor and the last weeks I spent a lot of my time on this project and my family was not so happy about it. Feel free to analyse it yourself and share the findings here or support me so I can convict my family to work further on this project 😊

**Comment by gazpachoking** [comment]
I'll try to poke around when I get some time to see what's possible.
