### ISSUE TITLE
renamed asyncio-mqtt

### ISSUE THREAD

**Issue by neildsb** [DeebotUniverse/Deebot-4-Home-Assistant#380]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

renamed asyncio-mqtt

still a problem with 1.6.1 :-(

This error originated from a custom integration.

Logger: mqtt
Source: custom_components/deebot/hub.py:12
Integration: Deebot 4 Home Assistant (documentation, issues)
First occurred: 10 July 2023 at 9:32:56 pm (1 occurrences)
Last logged: 10 July 2023 at 9:32:56 pm

We renamed asyncio-mqtt to aiomqtt and released a version 1.0.0 in the process. This is the last release under the asyncio-mqtt name. You can find the new repository at https://github.com/sbtinstruments/aiomqtt

### Diagnostics information

Home Assistant 2023.7.1
Supervisor 2023.07.1
Operating System 10.3
Frontend 20230705.1 - latest

### Anything in the logs that might be useful for us?

```txt
https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues/374
```

**Comment by edenhaus** [comment]
I can upgrade after https://github.com/sbtinstruments/aiomqtt/pull/232 is merged as I found a bug during testing the upgrade.
The integration is working as normal. Please ignore the warning in the meantime
