### ISSUE TITLE
Sensors and map not working with 950

### ISSUE THREAD

**Issue by jaczkooob** [DeebotUniverse/Deebot-4-Home-Assistant#386]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

I have ozmo 950 and I tried to add map but i got only error and all sensors are disabled

![image](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/118253315/008877a3-30ee-4c4f-a5ca-90c74d6a269a)

### Diagnostics information

[deebot-a20fb494ad7c6d0461535aadbf7c6cea-OZMO-7fb809e863672f0a31d1e6f22b20b512.json (1).txt](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/12105181/deebot-a20fb494ad7c6d0461535aadbf7c6cea-OZMO-7fb809e863672f0a31d1e6f22b20b512.json.1.txt)

**Comment by edenhaus** [comment]
You need to enable the sensors which you need as it is written in the docs https://deebot.readthedocs.io/integrations/home-assistant/entities/

**Comment by jaczkooob** [comment]
Can you explain where im need to enable it because i don't know how to do that

**Comment by edenhaus** [comment]
Settings -> Integrations -> Deebot 4 Home Assistant -> Entities

Then select all entities you want to use and then click on activate in the menu on the top

**Comment by jaczkooob** [comment]
Thanks
