### ISSUE TITLE
Shortcut Command to remove current Map or Restore Map Backup ???

### ISSUE THREAD

**Issue by tantai251295** [DeebotUniverse/Deebot-4-Home-Assistant#388]
### Question

When I get my map to Home Assistant, it error map because mixed previous map and new map.

What command to remove current map or restore backup map ???

<img width="498" alt="Screenshot 2023-07-26 at 15 13 09" src="https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/70562867/8f870597-a4a3-4d79-8cc7-44fcde13cad8">
<img width="594" alt="Screenshot 2023-07-26 at 15 17 10" src="https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/70562867/d34ae3c8-9308-4a1a-b328-4fa3565d7956">

**Comment by edenhaus** [comment]
I cannot write you the correct command as my model is not supporting (unfortunately) backups. Can you intercept the traffic of the app and check it yourself?

**Comment by tantai251295** [comment]
Yeah, I found command to delete map at https://deebot.readthedocs.io/advanced/data_types/json/commands/map/ is clearMap. After that, reclean to mapping. 
Thank you
