### ISSUE TITLE
HA 2023.8 beta error installing deebot-client 2.0.0

### ISSUE THREAD

**Issue by m7r** [DeebotUniverse/Deebot-4-Home-Assistant#390]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

After update to HA 2023.8 beta 0 and HAOS 10.4 the integration can not install deebot-client and fails to load.

## System Information

version | core-2023.8.0b0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4993
Installed Version | 1.32.1
Stage | running
Available Repositories | 1264
Downloaded Repositories | 16

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.4
-- | --
update_channel | beta
supervisor_version | supervisor-2023.07.2
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 117.3 GB
disk_used | 10.8 GB
healthy | true
supported | true
board | yellow
supervisor_api | ok
version_api | ok
installed_addons | Piper (0.1.3), ESPHome (2023.7.0), eufy-security-ws (1.5.2-1), Studio Code Server (5.9.0), Advanced SSH & Web Terminal (15.0.5)

</details>

<details><summary>Husqvarna Automower</summary>

can_reach_server | ok
-- | --

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 8
views | 4
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 18. Juli 2023 um 22:36
-- | --
current_recorder_run | 27. Juli 2023 um 16:12
estimated_db_size | 171.51 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Anything in the logs that might be useful for us?

```txt
error: Cannot install deebot-client==2.0.0
because these package versions have conflicting dependencies
```

### Additional information

deebot-client 2.1 will install but integration still needs updates for changes.

**Comment by townsmcp** [comment]
Same issue for me as well

**Comment by edenhaus** [comment]
I just released [2.0.0b0](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/releases/tag/2.0.0b0). Can you please test it and give me feedback.
Thanks :)

**Comment by purcell-lab** [comment]
Thanks, that has brought my Ecovacs back to life.

![Screenshot_20230729-205727](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/79175134/5b698495-1cef-4d77-a0e8-e22cf573652c)

**Comment by m7r** [comment]
Can confirm it works again

**Comment by edenhaus** [comment]
Thanks for your feedback :)

**Comment by townsmcp** [comment]
Working for me as well. Thanks for sorting it out
