### ISSUE TITLE
Can't control Vacuum Cleaner of Chinese version , 

### ISSUE THREAD

**Issue by huynkprovn** [DeebotUniverse/Deebot-4-Home-Assistant#395]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

I have check , have did and toid  black_list_.xxxxxx   in request and reponse frome ecouser.net 

### Diagnostics information

I have check , have did and toid  black_list_.xxxxxx   in request and reponse frome ecouser.net

**Comment by edenhaus** [comment]
I need more information.. If you have configured already, then please download and add the diagnostic information.

In addition I need debug logs to identify the problem

**Comment by huynkprovn** [comment]
![Screenshot_2](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/9349575/64286157-8282-42ab-b929-0a04df66ac49)
![Screenshot_4](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/9349575/3ecedbcf-703d-4e88-8a4f-47c7c6a7d74c)
i'm add my vacuum ,and connect but, can't control my vacuum.

**Comment by edenhaus** [comment]
Please attach the diagnostic information and also debugs logs without I cannot help you
