### ISSUE TITLE
Error after update to 2023.8.0 : Unable to install package deebot-client==2.0.0

### ISSUE THREAD

**Issue by maurizioandreotti60** [DeebotUniverse/Deebot-4-Home-Assistant#398]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [ ] I have installed the latest version

### The problem

After the update to HA Core 2023.8.0 Deebot integration fails to start with errors.

### Diagnostics information

Unable to install package deebot-client==2.0.0: ERROR: Cannot install deebot-client==2.0.0 because these package versions have conflicting dependencie
Unable to install package deebot-client==2.0.0: ERROR: Cannot install deebot-client==2.0.0 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.1.2 -> 23.2.1 [notice] To update, run: pip install --upgrade pip

**Comment by edenhaus** [comment]
Can you please provide more information? Which type of HA installation are you using?
Which other components have you installed?

**Comment by maurizioandreotti60** [comment]
> Can you please provide more information? Which type of HA installation are you using? Which other components have you installed?

I have HAOS running in a VM on a Synology NAS.
This is a simple test environment where I installed few components.

**Comment by maurizioandreotti60** [comment]
I see now that version 2.0.0 has been released and the issue is fixed!

**Comment by Magicpulse** [comment]
Have the same issue on HAOS.

**Comment by edenhaus** [comment]
**Please update to the latest version!** Hacs should offer you an update

**Comment by Magicpulse** [comment]
Ok, update appeared few min ago... I've updated and issue is now fixed.

**Comment by maurizioandreotti60** [comment]
> Ok, update appeared few min ago... I've updated and issue is now fixed.

The sensor live_map is available to you?
https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues/399
