### ISSUE TITLE
live_map sensor unavailable after updating to r 2.0.0

### ISSUE THREAD

**Issue by maurizioandreotti60** [DeebotUniverse/Deebot-4-Home-Assistant#399]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

I updated the component to fix the startup issue after upsate of HA 2023.8.0 and now the component works, but sensor live_map is unavailable.

### Diagnostics information

![immagine](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/27202392/a820f36d-1eba-4eec-976a-cef5da96dbc8)
![immagine](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/27202392/cac9e999-11b0-4c1f-a98f-b939d4bade02)

**Comment by dstewen** [comment]
Not working for me either. Was working prior to the update.

HAOS latest version with r 2.0.0 of the deebot addin

![image](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/42883717/abfd8399-b8e0-4c0d-b6b7-6af95bbc5580)

**Comment by edenhaus** [comment]
Please read the release notes. There where breaking changes. The camera was replaced by the image entity

**Comment by dstewen** [comment]
Can I request a documentation update with an example of the new format please? https://deebot.readthedocs.io/integrations/home-assistant/examples/ui/advanced/ still references the camera entity.

I searched for any entities starting with image and have no results. So I'm unsure how I should reference the entity in the advanced card template? 

![image](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/42883717/a662621a-e0eb-4b45-8d50-a983e781802e)
