### ISSUE TITLE
Advanced template incorrect - still references camera entity

### ISSUE THREAD

**Issue by dstewen** [DeebotUniverse/Deebot-4-Home-Assistant#401]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

Can I request a documentation update with an example of the new format please? https://deebot.readthedocs.io/integrations/home-assistant/examples/ui/advanced/ still references the camera entity.

I searched for any entities starting with image and have no results. So I'm unsure how I should reference the entity in the advanced card template? 

### Diagnostics information

HAOS with r2.0.0 of deebot

### Additional information

![image](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/42883717/279137c4-ac5c-4f20-bd98-38b1c945d9c7)

**Comment by edenhaus** [comment]
You only need to replace every the `camera` with the `image` entity.

Please feel free to open a PR to fix this issue :) I'm currently short on time

**Comment by thomaspalmdk** [comment]
I think I had the same problem as you. There were no "image"-entity.
I did this:
- In integrations clicked on "Deebot 4 Home Assistant"
- I then see "1 unit and 28 entities" and clicked the 28 entities
- In my case there were an entity called "Map" which was disabled
- Clicked the disabled entity and clicked the "cog"-icon in the top
- Enabled the entity by switching it on
- Reloaded the "Deebot 4 Home Assistant" integration

Now I have an "image"-entity.

**Comment by dstewen** [comment]
Thank you @thomaspalmdk. That helped a lot. Working now.

**Comment by bogorad** [comment]
> * In my case there were an entity called "Map" which was disabled

Thank you so much!
