### ISSUE TITLE
500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by JeedHome44** [DeebotUniverse/Deebot-4-Home-Assistant#407]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed/try to install the latest version

### The problem

Hello,

I have this Message when i want to configure thies integration !

`Erreur
Le flux de configuration n'a pas pu être chargé: 500 Internal Server Error Server got itself in trouble`

### On which deebot vacuum you have the issue?

Deebot Ecovacs T20

### Which version of the Deebot component are you using?

XXXX

### Which version of Home Assistant are you using?

XXXX

### What type of installation are you running?

Home Assistant OS

### Instance type

None

**Comment by edenhaus** [comment]
Please fill out the issue template completely. With `XXX`, I cannot help you.

Also please activate debug logs

**Comment by Rolsieya** [comment]
I also encountered the same problem, I downloaded the code and copied it into the `custom_components `folder.
But when I initialized the configuration, I received the following error message:
![image](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/30484799/8df6f931-904a-44e0-910b-d9bf41dd64e9)
![image](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/30484799/2de58e09-e204-4ed4-bd73-613710c89ba6)
![image](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/30484799/5458b3a3-79a6-4339-b382-ce145d9a2f89)

Did I missing any dependencies?

**Comment by Rolsieya** [comment]
Sorry, it's my problem, I found out after installing `HACS `that I downloaded version 2.0, but my HomeAssistant version should use  version 1.6

**Comment by JeedHome44** [comment]
> Sorry, it's my problem, I found out after installing `HACS `that I downloaded version 2.0, but my HomeAssistant version should use  version 1.6

Can you say me how you resolv this problem ?

**Comment by Rolsieya** [comment]
> > Sorry, it's my problem, I found out after installing `HACS` that I downloaded version 2.0, but my HomeAssistant version should use  version 1.6
> 
> Can you say me how you resolv this problem ?

First of all, you need to confirm whether your `HA` version and `deebot` version match, it is recommended that you use `HACS` to install the plugin, it will prompt you which version of deebot is suitable for your `HA`
