### ISSUE TITLE
Device not found despite being on supported

### ISSUE THREAD

**Issue by BaptainCeans** [DeebotUniverse/Deebot-4-Home-Assistant#409]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

I am trying to connect to my N8 plus. It keeps saying no supported devices. I have checked that my username and password are correct and I have been using AU and EU for country and continent respectively. I also tried ww for continent and this was still not working. 
![image](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/80022703/b5ab61d9-45f8-48db-897a-ba1849bbde46)

### Diagnostics information

I can't see any place to pick up the logs. Not sure if they'll be needed.

**Comment by edenhaus** [comment]
Please activate debug logs and attach them here so I can help you solve your issue :)
