### ISSUE TITLE
how to add multiple rooms with the same name

### ISSUE THREAD

**Issue by modparts** [DeebotUniverse/Deebot-4-Home-Assistant#413]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

I have multiple bathrooms like this:

Rooms
```
dining_room: 0
bathroom:
  - 8
  - 7
  - 3
kitchen: 4
study: 2
living_room: 5
```

what do i put here to make it bathroom 8?

  unique_id: deebot_robot_queue
    # Add for each room the following. Change room_name accordingly
    - unique_id: deebot_robot_queue_dining_room
      name: deebot_stoffy_queue_bathroom
      # room_name must match the room name provided by the vacuum
      state: >
        {% set room_name = "bathroom" %}
        {% set queue = trigger.to_state.state.split(",") %}
        {{ queue.index(room_name)+1 if room_name in queue else 0 }}

### Diagnostics information

none

**Comment by edenhaus** [comment]
The advanced example cannot distinguish between rooms of the same category. You can adjust it to directly pass the id instead of the name

**Comment by modparts** [comment]
> The advanced example cannot distinguish between rooms of the same category. You can adjust it to directly pass the id instead of the name

Where do i find the id or is it just the number?

**Comment by edenhaus** [comment]
The vacuum entity has the attribute `rooms`. This dictionary has the room name as key and the id as value.

For example, in your case, the living room has the id 5.

**Comment by dunkelheim** [comment]
@edenhaus is there an example for this. I don't get trough what key and value means for the code.
To not post a new issue.: I got to this issue because I have two bathrooms and three corridors which I wanted to be my problem solver. Whenever I choose one of these two to be cleaned, deboot changed one of the rooms to clean to the loundry (id 0)

**Comment by edenhaus** [comment]
The advanced example is the dashboard I use. As I don't have rooms of the same type, I didn't extend the example to work with them. Feel free to open a PR to add support for it. As far as I know, there is no example for it
