### ISSUE TITLE
User input malformed

### ISSUE THREAD

**Issue by V2RaySSR** [DeebotUniverse/Deebot-4-Home-Assistant#417]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

I enter the user ID and password, and I can see the device normally, but when I click Continue, an error occurs.
" User input malformed: Value should be a list for dictionary value @ data['devices'] "
Tried many times and also reinstalled HA.

why is that

I even tried downloading and decompressing the installation package, but the result was the same

### Diagnostics information

<img width="386" alt="截屏2023-09-08 14 01 48" src="https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/59167743/26c4c606-4108-4ddb-b5b0-c090bd1e9563">
<img width="578" alt="截屏2023-09-08 14 01 09" src="https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/59167743/68e47c03-631b-4c00-8def-20c527ece569">

**Comment by edenhaus** [comment]
Which version of HA are you using?

**Comment by adsvbijod** [comment]
same issue with HA 2023.9.0, but works flawlessly on 2023.8.0
upgrading again to 2023.9.0 after integration of the deebot does also seem to work.

**Comment by edenhaus** [comment]
Will be fixed with https://github.com/home-assistant/frontend/pull/17868
