### ISSUE TITLE
Setup failed for deebot: Integration not found.

### ISSUE THREAD

**Issue by neildsb** [DeebotUniverse/Deebot-4-Home-Assistant#426]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

I upgraded to 2.1.0 and had the following error

Logger: homeassistant.setup
Source: setup.py:193
First occurred: 3:13:11 pm (1 occurrences)
Last logged: 3:13:11 pm

Setup failed for deebot: Integration not found.

### Diagnostics information

Home Assistant 2023.9.2
Supervisor 2023.09.2
Operating System 10.5
Frontend 20230911.0 - latest

**Comment by snappingneuron** [comment]
Same here, new update borked everything.

**Comment by cash83** [comment]
after update integration not found.

**Comment by xPudda** [comment]
Same here, integration not found.

Logs:

2023-09-24 17:35:14.699 ERROR (SyncWorker_1) [homeassistant.loader] The custom integration 'deebot' does not have a valid version key () in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details

2023-09-24 17:35:33.597 ERROR (MainThread) [homeassistant.setup] Setup failed for deebot: Integration not found.
homeassistant.loader.IntegrationNotFound: Integration 'deebot' not found.

**Comment by RasmusC92** [comment]
Hi y'all.

I know that there already is some reports on this issue, i just want the auther to know, that there is one more :-)

Today, i updated from version 2.0.0 to 2.1.0 and now Dobbie is gone! (Maybe someone gave him a sock...)

Logs and some screenshots is attached to this post :-)

I figured out that i can remove the integration and then install version 2.0.0 again, which is still working.

![Poor Dobbie is unavailable](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/76855261/eadb0418-dbf2-46e2-ae7b-bea8c1d6df86)
[home-assistant_2023-09-24T16-07-50.989Z.log](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/12709079/home-assistant_2023-09-24T16-07-50.989Z.log)
[Logs from GUI.txt](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/12709080/Logs.from.GUI.txt)

**Comment by RasmusC92** [comment]
> Hi y'all.
> 
> I know that there already is some reports on this issue, i just want the auther to know, that there is one more :-)
> 
> Today, i updated from version 2.0.0 to 2.1.0 and now Dobbie is gone! (Maybe someone gave him a sock...)
> 
> Logs and some screenshots is attached to this post :-)
> 
> I figured out that i can remove the integration and then install version 2.0.0 again, which is still working.
> 
> ![Poor Dobbie is unavailable](https://user-images.githubusercontent.com/76855261/270176946-eadb0418-dbf2-46e2-ae7b-bea8c1d6df86.png) [home-assistant_2023-09-24T16-07-50.989Z.log](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/12709079/home-assistant_2023-09-24T16-07-50.989Z.log) [Logs from GUI.txt](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/12709080/Logs.from.GUI.txt)

A little update here!
I just tried to install the update again and restart HA, then open the manifest file at put in the version "2.1.0" where there was nothing written and gues what... IT WORKS :-)

![image](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/76855261/214aee5b-1151-4489-b2d9-6cd61faae79d)

**Comment by imightbelosthere** [comment]
> > Hi y'all.
> > I know that there already is some reports on this issue, i just want the auther to know, that there is one more :-)
> > Today, i updated from version 2.0.0 to 2.1.0 and now Dobbie is gone! (Maybe someone gave him a sock...)
> > Logs and some screenshots is attached to this post :-)
> > I figured out that i can remove the integration and then install version 2.0.0 again, which is still working.
> > ![Poor Dobbie is unavailable](https://user-images.githubusercontent.com/76855261/270176946-eadb0418-dbf2-46e2-ae7b-bea8c1d6df86.png) [home-assistant_2023-09-24T16-07-50.989Z.log](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/12709079/home-assistant_2023-09-24T16-07-50.989Z.log) [Logs from GUI.txt](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/12709080/Logs.from.GUI.txt)
> 
> A little update here! I just tried to install the update again and restart HA, then open the manifest file at put in the version "2.1.0" where there was nothing written and gues what... IT WORKS :-)
> 
> ![image](https://user-images.githubusercontent.com/76855261/270177618-214aee5b-1151-4489-b2d9-6cd61faae79d.png)

Can confirm that this allows you to get the Integration available again on HA.
Thank you @RasmusC92 for sharing the workaround you've applied.

**Comment by cash83** [comment]
> > > Hi y'all.
> > > I know that there already is some reports on this issue, i just want the auther to know, that there is one more :-)
> > > Today, i updated from version 2.0.0 to 2.1.0 and now Dobbie is gone! (Maybe someone gave him a sock...)
> > > Logs and some screenshots is attached to this post :-)
> > > I figured out that i can remove the integration and then install version 2.0.0 again, which is still working.
> > > ![Poor Dobbie is unavailable](https://user-images.githubusercontent.com/76855261/270176946-eadb0418-dbf2-46e2-ae7b-bea8c1d6df86.png) [home-assistant_2023-09-24T16-07-50.989Z.log](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/12709079/home-assistant_2023-09-24T16-07-50.989Z.log) [Logs from GUI.txt](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/12709080/Logs.from.GUI.txt)
> > 
> > 
> > A little update here! I just tried to install the update again and restart HA, then open the manifest file at put in the version "2.1.0" where there was nothing written and gues what... IT WORKS :-)
> > ![image](https://user-images.githubusercontent.com/76855261/270177618-214aee5b-1151-4489-b2d9-6cd61faae79d.png)
> 
> Can confirm that this allows you to get the Integration available again on HA. Thank you @RasmusC92 for sharing the workaround you've applied.

this way it was resolved

**Comment by townsmcp** [comment]
@RasmusC92 thanks for the tip of updating the manifest file. Worked for me

**Comment by geofffarmer** [comment]
Thanks, @RasmusC92. Working again.

**Comment by edenhaus** [comment]
It was fixed with a new Version. The version is automatically set with a workflow during the release, but it failed to detect the version. Added a check to prevent this issue in the future with #429
