### ISSUE TITLE
Live Map disappear

### ISSUE THREAD

**Issue by Husk84** [DeebotUniverse/Deebot-4-Home-Assistant#431]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

A couple of updates ago, I lost totally the entity of the Live Map. Now, if I enter and check, the Live Map sensor is "not available" and if I enter I see a warning like "The entity is not provided any more from this integration".
Is it possible to understand what is happening?
My device is a T8 Family (T8 ozmo) and the live map was correctly shown in the past.

Thanks for you help!

### Diagnostics information

I don't have any error or diagnostics to download. IF you need, let me know and I will be more than happy to share everything with you.

**Comment by edenhaus** [comment]
You probably didn't read the release notes before updating.
In Version [2.0.0](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/releases/tag/2.0.0) there was some breaking changes including:

> Replace camera entity by image entity and renamed it to map @edenhaus
The state will show the last time, when the map was updated.
The map will at most updated ones a second.

Did you enable the new `image` entity?

**Comment by Husk84** [comment]
You're right! I was totally miss this part of the 2.0.0 release note :(
Thanks for the hint!
