### ISSUE TITLE
Sensor "stats_total_area" not updated every time

### ISSUE THREAD

**Issue by monotonus** [DeebotUniverse/Deebot-4-Home-Assistant#439]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

The called sensor is very unreliable as it not updates during cleaning like "stats_area" and only updates sometimes when back in the loading station.

### Diagnostics information

Home Assistant 2023.9.2

Deebot T9

**Comment by edenhaus** [comment]
The sensor is updated, when the bots sends the report event.
The vacuum bot and ecovacs decides when to sent the event.
Nothing I can do about it.

Are you sure you get all events from the bot? Is there something in the log?
