### ISSUE TITLE
Deebot Ozmo 905 not supported?

### ISSUE THREAD

**Issue by Berto93** [DeebotUniverse/Deebot-4-Home-Assistant#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

Hello! I tried to integrate deebot ozmo 905 but all sensors are unavailable (can’t get neither status or battery state), in unknown status. 
Thanks for support.

### On which deebot vacuum you have the issue?

Deebot Ozmo 905

### Which version of the Deebot component are you using?

0.1.2

### Which version of Home Assistant are you using?

2021.11.5

### What type of installation are you running?

Home Assistant Core

### Country

It

### Continent

Eu

**Comment by edenhaus** [comment]
Currently your model is not supported as written in the [docs](https://deebot.readthedocs.io/home/models/#Model%20support)
