### ISSUE TITLE
Individual rooms are not permanently marked and show u..

### ISSUE THREAD

**Issue by MorreMor** [DeebotUniverse/Deebot-4-Home-Assistant#445]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

Everything works. But the individual rooms e.g. Kitchen etc. are not permanently marked. So I don't know which room is in the queue and which isn't. Where could the error be buried? Scripts run without errors, input queue selects the individual rooms but you don't remain marked and don't get any numbers :-(

### Diagnostics information

.

**Comment by edenhaus** [comment]
Please upload the diagnostic information, which will help me to get all required data.

I can not follow you. Please extend your description. Which queue you mean?
