### ISSUE TITLE
Deebot 4 Home Assistant will not load: Setup failed for custom integration 'deebot': Requirements for deebot not found: ['deebot-client==3.0.1'].

### ISSUE THREAD

**Issue by chrisuk-web** [DeebotUniverse/Deebot-4-Home-Assistant#471]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

Error after upgrading to core-2023.12.0b1:

Setup failed for custom integration 'deebot': Requirements for deebot not found: ['deebot-client==3.0.1'].
01:49:06 – (ERROR) setup.py
Unable to install package deebot-client==3.0.1: ERROR: Cannot install deebot-client==3.0.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
01:49:06 – (ERROR) util/package.py - message first occurred at 01:49:01 and shows up 3 times

### Diagnostics information

I do not have this.

### Anything in the logs that might be useful for us?

```txt
Please see above
```

**Comment by SolarSciencePup** [comment]
Same here

**Comment by edenhaus** [comment]
Which version are you using?
Does upgrading to the latest beta version solve your issue?

**Comment by sharkyy** [comment]
I have the same issue, Just updated to 2023.12.0b2 and still Not working properly.

**Comment by edenhaus** [comment]
Which version of this integration have you installed via hacs? Did you also install the latest beta version (https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/releases/tag/3.0.0b0)?

**Comment by sharkyy** [comment]
Indeed, the latest Beta (3.0.0b0) fixes this issue for me, thanks a lot for your Support, Guys!

**Comment by edenhaus** [comment]
Release new stable version and this problem should be solved
