### ISSUE TITLE
Deebot Already Configured 

### ISSUE THREAD

**Issue by bobdivx** [DeebotUniverse/Deebot-4-Home-Assistant#478]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

Can't add my bot back, it tells me it's already set up when no entity exists

I tried to remove the components and install it again, I rebooted HA. always the,same problem 

Thank you

### Diagnostics information

haos install
Is there a cache to empty or something else?

**Comment by bobdivx** [comment]
Cette erreur provient d'une intégration personnalisée

Logger: deebot_client.hardware.deebot
Source: custom_components/deebot/config_flow.py:262
Integration: Deebot 4 Home Assistant (documentation, issues)
First occurred: 11:10:12 (1 occurrences)
Last logged: 11:10:12

No capabilities found for 1vxt52. Using fallback.

**Comment by edenhaus** [comment]
If you get the log entry of your seconds comment, then you have set up the integration somehow.
Did you manually edit some files?

**Comment by bobdivx** [comment]
I tried the official integration first, then I removed it in order to use the HACS integration

**Comment by edenhaus** [comment]
Please check if an ecovacs config entry exists

**Comment by bobdivx** [comment]
I've checked under every possible name, there is none

**Comment by edenhaus** [comment]
Do you have or did you have install any other deebot integration other than this one?
