### ISSUE TITLE
Map no longer updating

### ISSUE THREAD

**Issue by mark-10-5** [DeebotUniverse/Deebot-4-Home-Assistant#48]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

I get this error in the logs when viewing the map on the vacuum card. I think this is an issue with this component and not the vacuum card. My map never updates after this error. Although it does update when i reboot home assistant.

```
Logger: deebot_client.message
Source: /usr/local/lib/python3.9/site-packages/deebot_client/message.py:58
First occurred: 14:41:24 (1 occurrences)
Last logged: 14:41:24
Could not parse getMapSet: {'type': 'vw', 'mid': '1309827822', 'subsets': [{'mssid': '27'}, {'mssid': '28'}, {'mssid': '29'}, {'mssid': '31'}, {'mssid': '32'}, {'mssid': '33'}, {'mssid': '34'}, {'mssid': '35'}, {'mssid': '36'}, {'mssid': '37'}, {'mssid': '38'}, {'mssid': '39'}, {'mssid': '40'}, {'mssid': '41'}]}

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 52, in wrapper
    response = func(cls, event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 108, in __handle_body_data
    return cls._handle_body_data(event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 97, in _handle_body_data
    return cls._handle_body_data_dict(event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/commands/map.py", line 114, in _handle_body_data_dict
    cls._ARGS_SET_ID: data["msid"],
KeyError: 'msid'
```
### On which deebot vacuum you have the issue?

Deebot Ozmo 950

### Which version of the Deebot component are you using?

0.2.0

### Which version of Home Assistant are you using?

2021.11.5

### What type of installation are you running?

Home Assistant Container

### Country

US

### Continent

NA

### Instance type

Cloud

**Comment by edenhaus** [comment]
Will be fixed with https://github.com/DeebotUniverse/client.py/pull/16.
If you want to fix it in the meantime on your instance, i comment in the PR, which line you need to change.

> My map never updates after this error. Although it does update when i reboot home assistant.

Are you sure? Is the map not updating also if you start a new job?
The error will be thrown on the end of a cleaning job to report all virtual walls, which are currently not supported. Support will be added in the above PR.

**Comment by mark-10-5** [comment]
So far i have noticed this when i start a job and the map doesn't update when it shows up in the log also. 
I will test some more as this has only happened one time so far that i have managed to make a note of it and exact timings.
