### ISSUE TITLE
All entities unavailible

### ISSUE THREAD

**Issue by compoundbow83** [DeebotUniverse/Deebot-4-Home-Assistant#498]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

Hello,
since the last HA Update to 2024.1.2 the integration don´t word.

All entities, are unavailible.

### Diagnostics information

I got this error in the logs:
No capabilities found for um2ywg. Using fallback.

**Comment by sdmeller** [comment]
Same here... Tried reconfigure the integration but it didn't help.
![Screenshot_20240107_103622_Home Assistant](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/6605538/11652569-9c5a-48f3-8628-c2a15e9e4a04)

**Comment by mrbungle64** [comment]
@sdmeller @compoundbow83 

Has this issue occurred since the HA 2024.1.2 update or since the last update of this integration?

**Comment by sdmeller** [comment]
I didn't notice when it happen. I updated yesterday, but I think it happened before because my "deebot started cleaning-switch on lights" automation - stopped working a few days ago.

Added log file. All "xxxxx" are my retractions.

Thank you!

[error_log.txt](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/13854130/error_log.txt)

**Comment by sdmeller** [comment]
Hmmm. Tried to connect to deebot via app and it says it is offline. I'm not at home now, will check later tonight.

**Comment by sdmeller** [comment]
My bad. Apologies. I was able to reboot my router remotely and deebot appeared. Only live map is unavailable.
Was it depriciated?

![Screenshot_20240107_114254_Home Assistant](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/6605538/849c8735-cc91-4869-ab92-bfce80252858)

**Comment by compoundbow83** [comment]
> @sdmeller @compoundbow83
> 
> Has this issue occurred since the HA 2024.1.2 update or since the last update of this integration?

I think yes, the issue occured since HA 2024.1.2 or 2024.1.1. But not since the last update of this integration.

**Comment by compoundbow83** [comment]
I restart my vaucum and now it works angain. But my configuration for the rooms don´t work anymore.

**Comment by edenhaus** [comment]
Closing this issue as rebooting router or vacuum solved it. If one entities is not working correctly, please create a new issue an attach logs to it.
