### ISSUE TITLE
HACS Download not working

### ISSUE THREAD

**Issue by GroveGuard** [DeebotUniverse/Deebot-4-Home-Assistant#510]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed/try to install the latest version

### The problem

Dear Support-Team,

when i click the "Download"-Button in HACS nothing happens.
Other Integrations work like a charm.

Greetings Anyo

### On which deebot vacuum you have the issue?

Deebot Ozmo 950

### Which version of the Deebot component are you using?

1.8.2

### Which version of Home Assistant are you using?

2024.1.3

### What type of installation are you running?

Home Assistant OS

### Country

de

### Continent

eu

**Comment by edenhaus** [comment]
There was never a `1.8.2` version for this compoent
