### ISSUE TITLE
[device_name]_map returns the map but no cleaning trace

### ISSUE THREAD

**Issue by bogorad** [DeebotUniverse/Deebot-4-Home-Assistant#522]
My device's name is 'bobik', so I used to get `image.bobik_map` and there was a URL ponting to a JPG. Now it returns this:

![image](https://github.com/DeebotUniverse/docs/assets/2777398/a2ee3bcf-76b0-461b-af50-1013a53c1b50)

I understand it's an XML file with BASE64-encoded PNG file. I successfully decode the BASE64 string, but the resulting image contains just the map, but no trace of the last cleaning route.

Image returned:

![image](https://github.com/DeebotUniverse/docs/assets/2777398/189b4eef-8487-40c2-b17b-51457d5814f5)

Image from HA:

![image](https://github.com/DeebotUniverse/docs/assets/2777398/27d2eb0c-e519-4f6b-8276-749b72fe3de2)

What changed and what do I need to call to get the proper map, just like HA itself displays?

**Comment by edenhaus** [comment]
Sorry, I can't follow you. HA is showing the correct image so everything is fine.
I don't get it where the first image comes from and which usecase that is.
The integration provides only one image entity to HA.

**Comment by bogorad** [comment]
When my deebot returns (state: docked after returning) I request `image.bobik_map` from HA. Here's what I get:

![image](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/2777398/4a0fb85c-9fdf-4379-a70c-b3f914c85b89)

Now I do curl -i <url provided> and get this:

![image](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/2777398/6ed7820c-728a-4309-b18f-09f86e955892)

Which is clearly not an image, but an XML. There's an image encoded in it. But it has no deebot's last route.

Previously the URL returned a JPG with the routes from the last cleaning. Do I need to decode xml/svg now?

**Comment by edenhaus** [comment]
We have switched to a [scalable vetor graphics (SVG)](https://de.wikipedia.org/wiki/Scalable_Vector_Graphics) in `3.1.0`. 
The PNG you are extracting from the XML is the background image. The bot's route is specified directly in the SVG.

Please learn how to use an SVG instead of a PNG or convert the SVG into a PNG if you need a PNG. But both are outside this integration's scope, and you can find all the required information on the internet.

**Comment by bogorad** [comment]
I see. thank you for the clarification.

**Comment by bogorad** [comment]
Now I have to render via an external service. Great :( 

You may close the issue.
