### ISSUE TITLE
Deebot Ecovas Intergration

### ISSUE THREAD

**Issue by becskenny** [DeebotUniverse/Deebot-4-Home-Assistant#528]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed/try to install the latest version

### The problem

I am trying to add ECOVACS vacuum via UI. Here is the error I encounter.

Error
This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant.

### On which deebot vacuum you have the issue?

Deebot N7 and N8

### Which version of the Deebot component are you using?

2.5.2

### Which version of Home Assistant are you using?

2024.1.6

### What type of installation are you running?

Home Assistant Core

### Country

CA

### Continent

NA

### Instance type

Cloud

**Comment by edenhaus** [comment]
You are probably using another custom component but not this one as the version `2.5.2` does not exist for this component.

**Comment by becskenny** [comment]
I am not using any custom components currently. I tried adding through yaml but that did not work and now I am trying to add through the UI. 

Maybe I added the wrong version number. Where do I find that?

**Comment by edenhaus** [comment]
> Which version of the Deebot component are you using?
> 2.5.2

What version did you insert here?
