### ISSUE TITLE
Deebot 901- Status Unknown

### ISSUE THREAD

**Issue by chris8837** [DeebotUniverse/Deebot-4-Home-Assistant#531]
### Question

https://flows.nodered.org/node/node-red-contrib-ecovacs-deebot

This node red integration works great. But this official one doesn’t?  Is there a way to merge this one into the official?  My 901 connects but I can’t seem to do anything. All the sensors are unknown

**Comment by mrbungle64** [comment]
@chris8837 

> This node red integration works great. But this official one doesn’t? Is there a way to merge this one into the official? My 901 connects but I can’t seem to do anything. All the sensors are unknown

What do you mean with "this official one"?

**Comment by chris8837** [comment]
I’m probably using the term wrong.  I should have said integration. Without using HACS.  ECOVACS integration is the one I’m getting the error on. With node red it connects to it and I can control. With the ecovacs integration which I believe this has been merged to?  I can’t pull sensors or control

**Comment by mrbungle64** [comment]
@chris8837 

Please check issue #360 for more information. The Node-RED integration does not have much to do with this 😉

**Comment by chris8837** [comment]
Got ya. I’ll try to close this one so I don’t sully up the issue thread.  If not take it down gentalmen!!
