### ISSUE TITLE
Advanced UI integration into Dwains Dashboard?

### ISSUE THREAD

**Issue by Chakkaaa** [DeebotUniverse/Deebot-4-Home-Assistant#538]
### Question

Hi Community,

I have an issue integrating the Advanced UI for Ecovacs Deebot into the Dwains Dashboard.

The Deebot Card needs the Button-Card and the Vacuum-Card integrations to work. On my default Overview the Card works great.
But when I try to integrate it into Dwains Dashboard it shows errors. I am not a pro when it comes to scripting but I am assuming since there is that one part to add some code to the RAW-Configuration editor for ecovacs deebot to work that this part is no longer accessed by Dwains Dashboard.

How can I workaround this?

![image](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/128637847/335f06cd-fe4b-4a0f-a477-c3ab0538eb89)

Any hint would be appreciated

Regards Sebastian

**Comment by edenhaus** [comment]
I#m not using  Dwains Dashboard and therefore I can't help you. I suggest you to ask for help there
