### ISSUE TITLE
Error parsing reportStats

### ISSUE THREAD

**Issue by rothnic** [DeebotUniverse/Deebot-4-Home-Assistant#62]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

I was investigating why my last cleaning information was only ever set to Unknown, and found an error in the logs of Home assistant. It appears that there are assumptions around parsing numbers from strings that need a little better handling. See [this StackOverflow explanation](https://stackoverflow.com/a/47764450). This error occurred when triggering a custom area from the app to try to get the coordinates from the last cleaning state to use for automation.

Error: `ValueError: invalid literal for int() with base 10: '-606.000000'`

### On which deebot vacuum you have the issue?

DEEBOT OZMO T8+

### Which version of the Deebot component are you using?

0.2.0

### Which version of Home Assistant are you using?

2021.11.5

### What type of installation are you running?

Home Assistant Core

### Country

us

### Continent

na

### Instance type

Cloud

### Anything in the logs that might be useful for us?

```txt
Logger: deebot_client.message
Source: /usr/local/lib/python3.9/site-packages/deebot_client/message.py:58
First occurred: 8:06:08 AM (3 occurrences)
Last logged: 12:23:47 PM

Could not parse reportStats: {'cid': '318598306', 'stop': 1, 'enablePowerMop': 0, 'powerMopType': 1, 'stopReason': 1, 'startReason': 1, 'type': 'customArea', 'mapCount': 16, 'area': 8, 'start': '1638711826', 'time': 1323, 'content': '-606.000000,11191.000000,2824.000000,8497.000000', 'aiopen': 1, 'aitypes': [], 'aiavoid': 0}
Could not parse reportStats: {'cid': '32995617', 'stop': 1, 'enablePowerMop': 0, 'powerMopType': 1, 'stopReason': 1, 'startReason': 1, 'type': 'customArea', 'mapCount': 16, 'area': 4, 'start': '1638715740', 'time': 1058, 'content': '3922.000000,9005.000000,6737.000000,4907.000000', 'aiopen': 1, 'aitypes': [], 'aiavoid': 0}
Could not parse reportStats: {'cid': '1140843480', 'stop': 1, 'enablePowerMop': 0, 'powerMopType': 1, 'stopReason': 1, 'startReason': 1, 'type': 'customArea', 'mapCount': 16, 'area': 3, 'start': '1638727729', 'time': 818, 'content': '3827.000000,9062.000000,6444.000000,5200.000000', 'aiopen': 1, 'aitypes': [], 'aiavoid': 0}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 52, in wrapper
    response = func(cls, event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 108, in __handle_body_data
    return cls._handle_body_data(event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 97, in _handle_body_data
    return cls._handle_body_data_dict(event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/messages/stats.py", line 33, in _handle_body_data_dict
    rooms=[int(x) for x in data.get("content", "").split(",") if x],
  File "/usr/local/lib/python3.9/site-packages/deebot_client/messages/stats.py", line 33, in <listcomp>
    rooms=[int(x) for x in data.get("content", "").split(",") if x],
ValueError: invalid literal for int() with base 10: '-606.000000'
```

**Comment by edenhaus** [comment]
I don't use personally `customArea` so i didn't notice this bug. Thanks for finding it :)

**Comment by rothnic** [comment]
Thanks for putting this together. I finally got tired of waiting for ecovacs to ever add any additional features to the app, so just now starting to play around with it.

**Comment by edenhaus** [comment]
Feedback is always welcome :) Together we can make a great HA integration.
