### ISSUE TITLE
Migration from And3rsL/Deebot-for-Home-Assistant

### ISSUE THREAD

**Issue by edenhaus** [DeebotUniverse/Deebot-4-Home-Assistant#7]
### Required steps for the migration process from [And3rsL/Deebot-for-Home-Assistant](https://github.com/And3rsL/Deebot-for-Home-Assistant)

- [x] Add this component to Hacs default hacs/default#1119 
- [x] Add documentation for the migration process DeebotUniverse/docs#35
- [x] Release stable version of [deebot-client](https://github.com/DeebotUniverse/client.py): [0.1.0](https://github.com/DeebotUniverse/client.py/releases/tag/0.1.0)
- [x] Release stable version of this component [0.1.0](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/releases/tag/0.1.0)
- [x] Adjust custom-wheels, to point to this repository https://github.com/home-assistant/wheels-custom-integrations/pull/537
- [x] Add replacement notice to old component (log warning on boot, which points to the migration docs) https://github.com/And3rsL/Deebot-for-Home-Assistant/pull/236
- [ ] After all users have migrated, delete And3rsL/Deebot-for-Home-Assistant from hacs default

### Reason

Since some time, I (@edenhaus) am the only person, which is maintaining the two repository and I don't get any reaction from the owner (@And3rsL).
As I don't have the required rights to change some settings, e.g. add pre-commit.ci or enable docs, I decided to create this Organization for it, so multiple person can be owners.
This organization is not only here for HA projects, but also for all deebot related projects. @mrbungle64 started to add his npm projects :)
Ecovacs change two times the communication protocol and my idea is to create one component, which supports all three and afterwards add it as official component.

**Comment by edenhaus** [comment]
A beta release is now available. As the PR hacs/default#1119 was mnot merged yet, you need to add this integration as custom integration to hacs.
Please test and give feedback for all (docs and integration)
Thanks in advance and a good 2021.11 release :stuck_out_tongue_closed_eyes:

**Comment by Edo78** [comment]
It's possible to install in while using the previous component or it has to be uninstalled?
There's a guide or a draft about the migration?

**Comment by edenhaus** [comment]
> It's possible to install in while using the previous component or it has to be uninstalled?

It is technical possible and I also had this written in the description, but unfortunately Hacs don't let you uninstall a component without removing the config entry first. So the most users need to remove the config entry first.

If you want keep the config entry, then you need to remove the old component manually. This is to advanced for the most users.


> There's a guide or a draft about the migration?

A draft can be found [here](https://deebot.readthedocs.io/en/latest/integrations/home-assistant/migration)
A link is already present in the release notes 😊

**Comment by aidbish** [comment]
All migrated without issue

**Comment by kauthmbt** [comment]
Migrated my N8 Pro successfully to the new release with the help of the draft.
Had some problems in the beginning where the status was reported as "unknown" all the time. But I was able to fix it by simply turning off and on again the Deebot.
Will provide further feedback if anything unusual will occur.

**Comment by edenhaus** [comment]
For now on, I use the `main` branch for beta testing. So if you want to test the beta, install the `main` branch via Hacs (Currently only this option is possible, as I haven't released a stable version yet).

**Comment by SmartM-ui** [comment]
Hi @edenhaus ,
I have the version of the custom "And3rsL / Deebot-for-Home-Assistant" and I tried to install your latest version, without uninstalling the previous one.

Unfortunately I cannot complete the migration and I find myself without the sensors of the Deboot (Ecovacs 920).

Could you tell me the steps to take? 
I also tried eliminating the integration and implementing it as new, but with no benefits.
Thanks in advance

<img width="614" alt="Schermata 2021-11-23 alle 11 17 44" src="https://user-images.githubusercontent.com/63554131/143045516-93ccdbb4-35b1-4bdd-a8e8-b05f98756bee.png">

**Comment by SmartM-ui** [comment]
> @SmartM-ui don't hijack a closed issue but open a new one the next time ;) As stated in the [migration guide](https://deebot.readthedocs.io/integrations/home-assistant/migration/#steps) you should remove the installation of `And3rsL/Deebot-for-Home-Assistant` before proceding.
> 
> I suggest to read all the steps before attempting to do something

Hi @Edo78 ,
I'm sorry, but some prefer to let the discussion continue, even if closed, if the problem is the same without opening new issues.

For information, I tried both removing the old custom (as written), and leaving the old custom, but the situation does not change.

I proceed to open new issues

**Comment by edenhaus** [comment]
@SmartM-ui Please open a new issue with debug logs.
I can only help you with logs. The screenshot will not help this time.
