### ISSUE TITLE
Command "clean" was not successfully

### ISSUE THREAD

**Issue by johnreind** [DeebotUniverse/Deebot-4-Home-Assistant#70]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

Hello,
since this morning that I upgraded to HA core 2021.12.1 and OS 7.0 I had this message in the log:
```


Logger: deebot_client.commands.common
Source: /usr/local/lib/python3.9/site-packages/deebot_client/commands/common.py:82
First occurred: 10:02:14 (1 occurrences)
Last logged: 10:02:14

Command "clean" was not successfully. body={'ret': 'ok', 'resp': {'header': {'pri': 1, 'tzm': 480, 'ts': '1639386133014', 'ver': '0.0.1', 'fwVer': '1.8.2', 'hwVer': '0.1.1'}, 'body': {'code': 0, 'msg': 'ok'}}, 'id': 'oe4W'}
```

Hower the status of Ecovacs 950 is reported correctly because I saw "clean" on HA when it starts cleaning.

I wold like to figure out if it is something to worry about or not.

Thanks.

### On which deebot vacuum you have the issue?

Debbot Ozmo 950

### Which version of the Deebot component are you using?

0.2.0

### Which version of Home Assistant are you using?

2021.12.1

### What type of installation are you running?

Home Assistant OS

### Country

it

### Continent

eu

### Instance type

Cloud

**Comment by edenhaus** [comment]
Can you please enable [debug logs](https://deebot.readthedocs.io/integrations/home-assistant/issues/) and attach them, when the issue happens again.

It's probably a edge case and I need more information to reproduce it.
